### ISSUE TITLE
this.next() is there, but iron-router does not know it.

### ISSUE THREAD

**Issue by SylvainBigonneau** [iron-meteor/iron-router#1005]
Ever since iron-router updated to 1.0.0, my routing does not want to work again. I took all the code down to the simplest I could, yet I still get the same error:

`Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?`

Here is my `lib/router.js`:

``` javascript
Router.configure({
    layoutTemplate: 'layout',
    loadingTemplate: 'loading'
});

Router.route('Home', {
    path: '/',
    waitOn: function() {
        return Meteor.subscribe('posts');
    },
    data: function() {
        return {posts: Posts.find()};
    }
});

var requireLogin = function() {
    if (!Meteor.user()) {
        this.render('login');
    }
    else
        this.next();
};

Router.onBeforeAction(requireLogin);
```

Given what I read in the guide, I don't understand why I still get this error.

**Comment by Rtransat** [comment]
Sorry to reopen this issue but I have the same problem here. I don't use the naxio:package
