### ISSUE TITLE
Config of bodyParser

### ISSUE THREAD

**Issue by manuel-schoebel** [iron-meteor/iron-router#1018]
I have seen that the bodyParser is now a standard middleware wich is a good thing.

The only problem I currently have is, that I cannot use it with my own settings. Even if I add it as a second middleware it does not help since the default ones settings are used.

Do you have any suggestions how to work around this? (without using a fork, what I currently do)

It is mainly the limit option that I cannot use with the default settings :(

**Comment by travisdahl** [comment]
I cant for the life of me get this to take affect. My code is as follows....

```
Router.configureBodyParsers = function() {
  this.onBeforeAction(Iron.Router.bodyParser.json({
    limit: '50mb'
  }));
  this.onBeforeAction(Iron.Router.bodyParser.urlencoded({
    extended: true
  }));
};

```

the urlEncoded part appears to be working but the limit just will not. Any blatantly obvious mistake im missing here?

**Comment by daslicht** [comment]
Same here , I tried:
```
if (Meteor.isServer) {
  Router.onBeforeAction(Iron.Router.bodyParser.json({limit: '50mb'}));
}
```

```
Router.route('/imageUpload', {where: 'server'})
  .post(function () {

    console.log("check", this.request.files); // undefined
    this.response.end('post request\n');
});
```

What am I missing please?

**Comment by stefan-wiesner** [comment]
Same here. Now my this.request.body is undefined ??? 

In some posts people suggest urlencoded (even for json) and in some json. I tried both. The error message went but an empty request body is not a real fix ;-)

How a bout this extended parameter? many say it should be true but I saw some examples with this set to false.

**Comment by daslicht** [comment]
Looks like we need to use busboy or any other middleware

**Comment by ThomsCass** [comment]
do we have a solution here ?

**Comment by evolross** [comment]
`Router.configureBodyParsers` could use some documentation. Finally unearthed it here. I'm able to get it to work and get it to shut off the default JSON parsing on every request.

One thing I struggled with was making sure the `type` field matches the request's `content-type`, otherwise the parser won't fire.
