### ISSUE TITLE
Hooks called twice on every rendering ? Error or "Feature" ?

### ISSUE THREAD

**Issue by TimoRuetten** [iron-meteor/iron-router#1031]
Hey!

I switched from an older version to version 1.0 and now I have the problem that the Hooks called twice. Here is an example of what I mean:

This is my code for one route:

``` javascript
Router.route('/search/:page?/:what?/:where?', function () {
    var params;
    params = this.params;

    this.wait(Meteor.subscribe('business_search', {what : params.what, where : params.where}));

    if (this.ready()) {
        console.log('############### THIS.READY() ###############');
        this.render('search_result');
    } else {
        this.render('loaderDefault');
    }

    this.render('searchBig', {
        to : 'top',
        data : {
            what : params.what,
            where : params.where
        }
    });

}, {
    name : 'search',
    onBeforeAction : function () {
        console.log('onBeforeAction called');
        this.next();
    },
    onAfterAction : function () {
        console.log('onAFTERAction called');
    }
});
```

After running this route directly OR when clickung on a link which is "linking" to this route the console has this output:

``` javascript
onBeforeAction called
onAFTERAction called
onBeforeAction called
############### THIS.READY() ###############
onAFTERAction called
```

As you can see the onBeforeAction and also the OnAfterAction is always called twice. 

I made a "test": When removing the "if (this.ready()) [...]" Block the Hooks are just called once per running ... so the this.ready() seems to be the problem ... but then I do not rly understand how to use this in the right way ?

**Comment by advany** [comment]
did anyone solf this? i have the same issue...

**Comment by advany** [comment]
No idea why but multiply:iron-router-progress is causing this. Removed it and the hook isn't called anymore @cmather @ndemoreau

**Comment by ahmadthd** [comment]
i am doing it this nasty way : (any suggestions)
onAfterAction: function () {
     if (typeof ranOnceCon == 'undefined')  {
          console.log("sendingLogMessage");
          Meteor.call('sendLogMessage');
          ranOnceCon = 1;
    }
}

**Comment by niranjans** [comment]
@cmather Hi Chris, I have reproduced the error. [Here] (https://github.com/niranjans/testRouter) is the Github repo. And you can test the problem [here] (http://testrouter1.meteor.com/). 

Right on the homepage, just open the browser console and you will notice that `WaitOn` and `data` are being run twice. When there is no `WaitOn`, then the data just runs once as normally is expected.

Let me know if I can help.

**Comment by abhirakshit** [comment]
I have seen this aswell. Is there some resolution to this?

**Comment by boris-petrov1214** [comment]
+1

```lang-none
I have also same problem.

waitOn: function() {
            console.log("subscribing");
            return [ Meteor.subscribe('companies')];
    },

subscribing logged twice.

**Comment by lorensr** [comment]
IR hooks are run reactively, so if there are any reactive data sources, like `Meteor.subscribe` or `Meteor.userId()`, the hook will be rerun whenever the data source changes (eg becomes ready or gets logged in)

**Comment by alochschmied** [comment]
My workaround (for now?) is similar to what @ahmadthd suggested:

```
onAfterAction: function() {
    if (Tracker.currentComputation.firstRun) {
        // called only once per route
    }
}
```

**Comment by phocks** [comment]
Like @advany I removed **multiply:iron-router-progress** and the problem of the action being called twice went away. So it seems to be related to that package. The problem is I would like to actually use that package. I might file a bug with them.

Also thanks to @alochschied for `if (Tracker.currentComputation.firstRun)` works like a charm to only run things once.

**Comment by advany** [comment]
I switch the flow router
