### ISSUE TITLE
Iron Router 1.0.x is eating CollectionFS download URLs

### ISSUE THREAD

**Issue by tanis2000** [iron-meteor/iron-router#1039]
It looks like something in Iron Router has changed in a way that the CollectionFS download URLs no longer work. Could you please help identify where the problem could be?
You can find more details there: https://github.com/CollectionFS/Meteor-CollectionFS/issues/472

**Comment by ColinRoache** [comment]
Did anyone confirm this fix?

I am getting the same error with these versions:
cfs:collection@0.5.5
cfs:filesystem@0.1.2
cfs:gridfs@0.0.33
iron:router@1.0.9

**Comment by ColinRoache** [comment]
I can confirm this is fixed. The error I received was due to having both a route and collection with the same name.
