### ISSUE TITLE
change route without invoking onRun

### ISSUE THREAD

**Issue by ccorcos** [iron-meteor/iron-router#1048]
I am only using my routes on the initial page load. After that, I'm handling all the animation and page transitions myself. But I wanted update the urls in the browser. For example

```
@route 'loginSignup',
  template: 'main'
  path: '/login-signup'
  onRun: ->
    if loggedIn()
      this.redirect 'home'
    this.next()
```

In main.rendered I have a bunch of reactive autoruns taking care of my views. And when the views change, I set the url with this:

```
@setRoute = (route, options) ->
    slug = Router.path(route, options).substring(1)
    url =  Meteor.absoluteUrl(slug)
    window.history.pushState('','',url)
```

Whenever I open the app on my iPhone through the local network, I get this error:

```
Error: Failed to execute 'pushState' on 'History': A history state object with URL 'http://localhost:3000/' cannot be created in a document with origin 'http://chets-mbp.local:3000'.
```

So I don't thing `window.history.pushState` is a good idea apparently. Any ideas?

Thanks

**Comment by vampirefan** [comment]
I have the same problem:
Just want to redirect user to another domain like "www.google.cn"
Router.go('http://www.google.cn") does not work any more?

**Comment by ccorcos** [comment]
Check out Flow Router. Its much more simple. I like it more
