### ISSUE TITLE
public folder and static files

### ISSUE THREAD

**Issue by dotnetwise** [iron-meteor/iron-router#1051]
How to tell iron router to ignore them and serve them accordingly?

**Comment by francisbyrne** [comment]
@cmather Just tried updating to 1.0.7 but the issue isn't fixed for me.

@hellogerard Thanks for the workaround. It works in Chrome but not in Safari.

More details with my code [here](https://stackoverflow.com/questions/28018018/how-to-link-downloadable-static-files-in-public-using-iron-router).

**Comment by hellogerard** [comment]
@francisbyrne Odd. It works for me in Safari on Mac OS.

**Comment by chicagogrooves** [comment]
Can there just be a `?iron-router-bypass=1` query flag? I'm trying to load static JS with script tags, the `_blank` workaround isn't going to work.

**Comment by foobarbecue** [comment]
I still have this problem with 1.0.7.

**Comment by rajit** [comment]
@chicagogrooves you don't need the `_blank_` workaround, the latest version is working fine for me.

**Comment by woniesong92** [comment]
On `Meteor 1.1.0.2` my image files that are located in `/public` are not served correctly.

**Comment by rahadiancs** [comment]
This still not working for sub directory.

I put images on /public/images/favicons/favicon.ico, but when I tried to access it, I got 404.

If I put it directly on images (/public/images/favicon.icon), it works, but I need to put it inside sub folder to organize it.

Is this also bug, or is this the intended behaviour?

**Comment by ryanbraving** [comment]
@rajit this problem still exists in latest Meteor version 1.4.2.6.
A quick fix is  to add a target="_self" attribute. It is working but what it does is like clicking back on the page which needs to load the page again. If we could do it through routing it was much nicer as there is no loading time involved.

**Comment by ryanbraving** [comment]
I still have this problem. Does anyone know how to fix this router issue?

**Comment by chrisbutler** [comment]
@ryanacme i can take a look if you can give me a reproduction

**Comment by ryanbraving** [comment]
@chrisbutler thanks a lot. it would be a great help. Here is my repo:
https://github.com/ryanacme/publicFolder_temp

**Comment by chrisbutler** [comment]
@ryanacme so your issue is not this, the symptom just seems similar because your code has other issues

your issue is with relative/vs absolute paths on the images... you need to put forward slashes before your ```{{img_src}}``` otherwise the images won't load correctly if you aren't on the root path

**Comment by ryanbraving** [comment]
Thanks heaps @chrisbutler . it was a great help. Now by having this forward slash my static images are working perfect but once I import images with absolute path (e.g. from web) then I face the same issue with those images. Since I know the issue now I think it would be easy to find a workaround.

**Comment by ryanbraving** [comment]
@chrisbutler I found it. I just add "forward slash" when I insert my static images into my collection on server code.
Thanks again.

**Comment by chrisbutler** [comment]
@ryanacme happy to help!
