### ISSUE TITLE
Disable the loading plugin

### ISSUE THREAD

**Issue by isAlmogK** [iron-meteor/iron-router#1063]
With the new version of iron-router the waitOn option will automatically use the loading plugin. However I'm using multiply:iron-router-progress so there is no point in having the loading text or spinner if that's already showing a loading progress bar. 

Is there a way to disable it didn't see anything in the guide?

**Comment by shividhar** [comment]
I can't seem to use the subscriptions hook on my Route Controllers. It loads the default template for a moment before loading the intended one. Help would be greatly appreciated.

**Comment by shividhar** [comment]
Found a fix for this. I stuck with the waitOn on the controller and the route. I just set a "loadingTemplate" in my route. Since I needed to have different loading templates depending on the device being used, so I just made a function that returned just the name of the loading template.
