### ISSUE TITLE
waitOn subscription that sends a Date.now() argument causes infinite loop

### ISSUE THREAD

**Issue by rlora** [iron-meteor/iron-router#1071]
Reproduction: https://github.com/rlora/iron-router-reactive-date-issue

Packages: 
 * iron:router 1.0.2
 * meteor-platform 1.2.0

To reproduce:
 * Start application
 * Point browser to /

Server log shows that the publication runs an infinite loop, and the page keeps loading all the time.

**Comment by elie222** [comment]
Using the above code didn't work for me. this.timestamp became a function, and even using the following code still caused the infinite loop problem:
```
this.timestamp = _.once(function () { return Date.now(); })();
```
