### ISSUE TITLE
spaces is GET query are not correctly handled

### ISSUE THREAD

**Issue by acemtp** [iron-meteor/iron-router#1088]
I created a server side get, in the request I have:

    originalUrl: '/page?text=c%2Bc%2Bc'

and this.params.query.text is converted into:

    text: 'c+c+c'

it's correct.

but if I do this request:

    originalUrl: '/page?text=c+c+c'

this.params.query.text is converted into:

    text: 'c+c+c'

but it should be:

    text: 'c c c'

**Comment by RodMagnuson** [comment]
I'm still encountering this and it seems to be only a problem with +s.

I'm trying to preserve a user's filter in an url's query string.

I've tried

    Router.go('Channel', { channelId: channelId }, { query: "filter=" + encodeURIComponent(filterText) });

and

    Router.go('/channel/' + channelId + "?filter=" + encodeURIComponent(filterText) );
to no avail.

If the user type Testing++ in the filter, the browser's url is http://localhost:3000/channel/someChannel?filter=Testing%2B%2B (correct), but the route's subscriptions function find this.params.query.filter as "Testing ", no pluses (incorrect).

**Comment by RodMagnuson** [comment]
function safeDecodeURIComponent (val) {
  try {
    return decodeURIComponent(val).replace(/\+/g, ' ');
  } catch (e) {
    if (e.constructor == URIError) {
      warn("Tried to decode an invalid URI component: " + JSON.stringify(val) + " " + e.stack);
    }

    return undefined;
  }
}

Looks like the code is purposely doing this

**Comment by RodMagnuson** [comment]
Here's the commit: https://github.com/iron-meteor/iron-url/commit/c86a087d72cdc524316762fa0a48db359099733b

**Comment by dweldon** [comment]
I had a similar problem recently when the query string was an encoded hash which was supposed to contain `+` symbols. I think the correct implementation would decode:

`text=c%2Bc%2Bc` -> `text=c+c+c`
and
`text=c+c+c` -> `text=c c c`

The current implementation is effectively doing two layers of decoding by replacing the `+`s at the end. In my opinion, the correct implementations are:

```js
decodeURIComponent(val.replace(/\+/g, ' '));

decodeURI(val.replace(/\+/g, ' '));
```

for `safeDecodeURIComponent` and `safeDecodeURI`, respectively.

**Comment by RodMagnuson** [comment]
Why is any special casing necessary? if c+c+c is passed to encodeURIComponent, then c%2Bc%2Bc is passed to decodeURIComponent c+c+c comes back.

**Comment by dweldon** [comment]
Because `+` is a substitute for `%20`, which makes for a weird [corner case](https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20). So `c+c` should actually decode to `c c` which isn't provided by `decodeURIComponent`.

**Comment by RodMagnuson** [comment]
Thanks for the explanation.

**Comment by cmather** [comment]
@dweldon, happened to see this issue float by. Sorry for the late responses. Does this need to be updated? Happy to give you commit rights if you'd like to make a change, or I can add this to my todo list.

**Comment by dweldon** [comment]
@cmather I have the fix and tests ready. Just give me commit rights on iron-url and I'll send a PR. Is a branch off `master` acceptable?

**Comment by cmather** [comment]
You can commit to master if the tests are passing. I'll add you. Doing a release is a bit more complicated but I'll try to get to it this week.

**Comment by Pagebakers** [comment]
Any eta on when this will be released?
