### ISSUE TITLE
onRun not running

### ISSUE THREAD

**Issue by frozeman** [iron-meteor/iron-router#1097]
Hi in two of my apps on Run is not firing.
I now created an repro and indeed it stopped working.

see: https://github.com/frozeman/meteor-iron-router-onrun

**Comment by elie222** [comment]
What ever happened with this issue? onRun seems to work for me half the time. Same app. Haven't changed anything, but it doesn't consistently run. @frozeman did you work out what your problem was?

**Comment by elie222** [comment]
So it does seem to work. It's just when there's a hot code push, onRun stops working - even for future page changes. If you click refresh it starts working again.
See here: https://github.com/iron-meteor/iron-router/issues/982
