### ISSUE TITLE
Setting controller option in Router.configure has no effect

### ISSUE THREAD

**Issue by apacala** [iron-meteor/iron-router#1126]
Using Meteor 1.0.1 and Iron.Router 1.0.3.

Taken straight from the [guide](https://github.com/EventedMind/iron-router/blob/devel/Guide.md#inheriting-from-route-controllers):

```javascript
ApplicationController = RouteController.extend({
  layoutTemplate: 'ApplicationLayout',

  onBeforeAction: function () {
    console.log('before layout');
    this.next();
  }
});

Router.configure({
  // this will be the default controller
  controller: 'ApplicationController'
});

Router.route('/test', {
  name: 'test'
});
```

Assuming that both `ApplicationLayout` and `Test` templates exist, test route doesn't use `ApplicationController` when visiting `/test` (no layout nor console output).

Defining `TestController` and making it inherit from `ApplicationController` works though. Is this an expected behavior or am I doing something wrong here?

**Comment by peterchoo** [comment]
I'm new to Meteor and IronRouter, but I believe that the issue lies here: https://github.com/EventedMind/iron-router/blob/devel/lib/router.js#L125

As far as I can tell the `route()` method doesn't use the Router's default options at all.  Should it be `opts = opts || Router.options;` ?

Issue still exists in 1.0.7

**Comment by rijk** [comment]
Second this! Just cost me an hour, as I was assuming I was doing something wrong since the guide explicitly states this use case:

```javascript
Router.configure({
  // this will be the default controller
  controller: 'ApplicationController'
});
```

Please fix or remove from the guide.

**Comment by lewislambert** [comment]
This is also causing me quite a lot of issues as I'm having to put a lot of extra code in, rather than use a customised default controller. Shame this was raised back in December and it's still not working.

**Comment by KyleKing** [comment]
Same here, any updates why?

**Comment by Pushplaybang** [comment]
??  any updates?  

love this package, and em, please let us know!
