### ISSUE TITLE
Button Click

### ISSUE THREAD

**Issue by sangyoo91** [iron-meteor/iron-router#1154]
When I click a button with this setting,

button type = "submit"

It will go to this route.

http://localhost:3000/action?

and show this 

Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/action?."

...

I have code to do some things within a js file using template events  submit.

**Comment by mattiemoon** [comment]
Hello.

I had a similar issue just now; I'd named the template events handler incorrectly (so I effectively didn't have a handler for the submit event). Check that they match up...

``` html
<template name="BLAH">
  <form id="MYFORM" action="action">
    <button type="submit">Submit</button>
  </form>
</template>
```

and...

``` javascript
Template.BLAH.events({
  'submit #MYFORM' : function(e, t) {
    e.preventDefault()
    ...
  });
});
```

**Comment by chrisbutler** [comment]
yep, the `e.preventDefault()` is crucial
