### ISSUE TITLE
No Way to Disable Iron-Router for a Route

### ISSUE THREAD

**Issue by jordangarside** [iron-meteor/iron-router#1165]
I can't find any option to disable Iron Router for a particular route or group of routes.
Say for example, any routes on '/cordova/*', I would like to use Angular UI Router and disable Iron Router.

**Comment by cleor41** [comment]
I would love to know how to do this also

**Comment by istarkov** [comment]
+1 i need this

**Comment by cleor41** [comment]
http://stackoverflow.com/questions/31035196/iron-router-conflict-with-angular-ui-router/31127432#31127432

Hopfully this works for you. I figured it out and put the solution here. You pretty much just use iron router to deliver the initial angular template
