### ISSUE TITLE
There is no way to disable client side

### ISSUE THREAD

**Issue by mitar** [iron-meteor/iron-router#1180]
If I want to run iron router only on the server side it seems that iron-router sill adds itself on the client, and injects its own templates there in the body? Is this possible to disable?

**Comment by mitar** [comment]
It seems you can do `Router.options.autoStart = false;` on the client and it will not autostart. Which allows you to not use iron-router on the client.

**Comment by jdmswong** [comment]
thank you @mitar

**Comment by WikiOops** [comment]
But in tutorial it's said client side route can be disabled.
Should be a bug?

**Comment by ianmedina0909** [comment]
Thanks to this info..

**Comment by aheiss1** [comment]
opera?
