### ISSUE TITLE
Routes with FS Collection {{this.url}} not rendering/displaying IE8

### ISSUE THREAD

**Issue by javierocanas** [iron-meteor/iron-router#1191]
I know maybe sounds weird, looking support for Internet Explorer 8 on 2015 but i'm from México and here like in some countries of Latin America still uses IE8 and IE9 specially on office, so for this project is very important.

So we have dynamic routes using Iron Router but it seems like, the dynamic routes with images dosnt work if you have a chance check this [page](http://padonde.mx/)

Is this a Iron router problem? or FSCollection url problem?

Actually the problem just appear when {{this.url}} have an image on it, if {{this.url}} is empty the route work.

Thanks in advice

**Comment by mzugn** [comment]
If someone comes across this situation, the solution is to add base64 polyfill (probably for the tokens used by CollectionFS) in case of IE8 and 9, it's not an issue with IronRouter.

**Comment by chrisbutler** [comment]
thanks @mzugn
