### ISSUE TITLE
How to abort move to another page with onStop?

### ISSUE THREAD

**Issue by hiphapis** [iron-meteor/iron-router#1195]
Using `onStop` I can intercept the router before a page transition. Is it possible to abort the page transition? I have tried returning `true` / `false` and calling `this.stop()` but nothing seems to work. Any help would be much appreciated.

**Comment by mpranjic** [comment]
You can't. See #698

**Comment by hiphapis** [comment]
@mpranjic Thanks! :cry:

**Comment by JamesLefrere** [comment]
@hiphapis How about https://github.com/ephemer/meteor-before-leave-previous ? I haven't tried it myself, but it could work...

**Comment by hellogerard** [comment]
I'd close this as a dupe of #698
