### ISSUE TITLE
Dubious `Router.current().params` array with object properties on Router.go()

### ISSUE THREAD

**Issue by dandv** [iron-meteor/iron-router#1213]
What exactly is the syntax for Router.go()? The [Guide](https://github.com/EventedMind/iron-router/blob/devel/Guide.md#named-routes) gives this example:

    Router.go('post.show', {_id: 1}, {query: 'q=s', hash: 'hashFrag'});

I've tried the call above in an event handler,

    Router.go('one', {_id: 1}, {query: 'q=s', hash: 'hashFrag'});

And `Router.current().params` *appears* to be an empty array. However, it's not exactly empty:

![image](https://cloud.githubusercontent.com/assets/33569/5990886/d6436852-a97d-11e4-849b-d8767ad0705a.png)

**Comment by dandv** [comment]
Here's a repo for reproduction: https://github.com/dandv/iron-router-bug-current-param

**Comment by lorensr** [comment]
Broken link, correct is:

https://github.com/dandv/iron-router-bug-current-params/

**Comment by dandv** [comment]
@lorensr: thanks, fixed the link. Deleting this...

**Comment by erasaur** [comment]
Properties on arrays aren't array elements, so it *is* an empty array, with some extra properties besides `length`.

**Comment by dandv** [comment]
@erasaur Correct, but it probably should be initialized with `{}`, not `[]`, for ease of debugging in the console.

**Comment by cmather** [comment]
Use console.dir(...) to show array props in the console. Params is an array to allow for wildcard params which are anonymous (eg positional with no name). So you access them by index like params[0] params[1].

**Comment by Sewdn** [comment]
You should just cats this array to an Object if you need to (as I do):
```
var params _.extend({}, Router.current().params);
```
