### ISSUE TITLE
The package cmather:iron-router at 0.8.1 is incompatible with Meteor 0.9.0 or later.

### ISSUE THREAD

**Issue by wedranb** [iron-meteor/iron-router#1225]
I have updated my meteor and meteor project. I'm using Iron-router and I got this error:

The package cmather:iron-router at 0.8.1 is incompatible with Meteor 0.9.0 or later.

**Comment by Tarang** [comment]
Iron router changed name. Remove the old and add the new

```
meteor remove cmather:iron-router
meteor add iron:router
```
