### ISSUE TITLE
ReferenceError Controller is not defined

### ISSUE THREAD

**Issue by mahmoudkm** [iron-meteor/iron-router#1226]
I am using iron-router in my Meteor app, and each time I try to add a new sub-controller to my AppController I get the error shown below (I have also included here the routing code in my app). After several trials, I found that when renaming AboutUsController to MAboutUsController I see no error and everything work just fine!! 

With few more tests I noticed that as long as any new controller name follow AppController (alphabetically) everything is working fine, else it crash...So for example if I named the new controller BppController it will work...but AooController won't work...so I was wondering does this have to do anything with the sequence those files are compiled by Meteor or is it an iron-router issue? Thanks

     /Users/mkm/.meteor/packages/meteor-tool/.1.0.40.n80bjt++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
         throw(ex);
           ^
    ReferenceError: AppController is not defined
        at app/both/controllers/aboutus.js:1:56
        at app/both/controllers/aboutus.js:5:3
        at /Users/mkm/meteor/projects/mshop/.meteor/local/build/programs/server/boot.js:205:10
Code I am using in my app:

    AppController = RouteController.extend({
      layoutTemplate: 'appLayout'
    });
    HomeController = AppController.extend({
    
    });
    DashboardController = AppController.extend({
    
    });
    AboutUsController = AppController.extend({  
    
    });

    Router.configure({
      controller: 'AppController',
      loadingTemplate: 'loading'
    });

    Router.map(function() {
    
      this.route('home', {
         path: '/',
         template: 'home',
         controller: "HomeController"        
      });

      this.route('aboutus', {
         path: '/aboutus',
         template: 'aboutus',
         controller: "AboutUsController"    
      });

      this.route('dashboard', {
         path: '/dashboard',
         template: 'dashboard',
         controller: "DashboardController"     
      });

    });

I am using iron:router@1.0.7 and Meteor 1.0.3.1

**Comment by mpranjic** [comment]
Is your code in the same file? What if you try ```controller: AppController``` (without quotes)?

**Comment by mahmoudkm** [comment]
No, each controller is in a single .js file all in the same /controllers folder

**Comment by mpranjic** [comment]
Then it looks like a meteor loading order.
Does it work if you move your router mappings outside of ```controllers``` ?

**Comment by mahmoudkm** [comment]
By moving appController.js to a sub-folder below /controllers folder, error is gone and everything is working fine. Thanks for your help.
