### ISSUE TITLE
Check if route exists

### ISSUE THREAD

**Issue by stlouisweb** [iron-meteor/iron-router#1234]
Is there a way to check if a route already exists before creating a new route, something like:
```
if (! Router.route('/')) {
  Router.route('/', function () {
    this.render('Home');
  });
}
```

**Comment by ramsaylanier** [comment]
Interesting...what would be a use case for this though? Wouldn't you already know your existing routes?

**Comment by stlouisweb** [comment]
I'm trying to build a package that extends these packages:  https://github.com/tomitrescak/meteor-uploads by creating drop in templates for an image uploader. These packages seem to depend on iron-router, so I'm trying to come up with a way to prevent the no route message from coming up in the browser if a route isn't specified for the template that the image upload templates are inserted into.

**Comment by PEM--** [comment]
In case, you would still need it:
```js
if (Router.routes[fields.slug] === void 0) {
  console.log('Route not found');
}
```
