### ISSUE TITLE
deployed app keeps showing "Organize" splash screen on IE

### ISSUE THREAD

**Issue by bastiaanterhorst** [iron-meteor/iron-router#1251]
Hi,
I have a peculiar issue where my deployed app keeps displaying the IR splash page inviting me to organize the app, but only in IE. I tested IE 10 and 11. The app (running at http://pattymorgan.net) is working fine in all other browsers I tested (Safari, Firefox, Chrome).

Needless to say, I do have a '/' route, which the splash page invites me to create (in coffeescript):
```
Router.route '/', { name: 'landing' }
```

The app is deployed on Heroku. I tried various different buildpacks, but that does not seem to make a difference. I searched the issues but did not see this specific issue yet. So that leaves a bit unsure on how to proceed. If anyone has any ideas of what I can try, I'd love to hear them.

Thanks!

**Comment by chrisbutler** [comment]
check the console

```
SCRIPT438: Object doesn't support property or method 'helpers' 
4690c22366527555e0455bf68654faa09603e1b7.js, line 454 character 5009
There is no route for the path:/ 
```
