### ISSUE TITLE
Cannot acces Meteor.user() data when using data for Iron Router

### ISSUE THREAD

**Issue by pasharayan** [iron-meteor/iron-router#1281]
I'm trying to get a user's profile information to populate some data that is required on a route. For some reason, Meteor.user() is returning undefined when being called upon in the data section of a route:

    Router.route('/', {
      name: 'homepage',
      data:function(){
        console.log(Meteor.user())
        var userData = Meteor.user()
        return{
          company: Companies.findOne({_id: userData.profile.companyId})
        }
      }
    })

Is there any way to access user data here?

**Comment by autodidacticon** [comment]
Publish the users collection and subscribe to it. Include the subscription in the waitOn function.

**Comment by chrisbutler** [comment]
@pasharayan does Meteor.userId() return anything?
