### ISSUE TITLE
iron router error in PRODUCTION preventing to access the app

### ISSUE THREAD

**Issue by nick-preda** [iron-meteor/iron-router#1282]
hi guys,
i'm experimenting issues with the iron router ONLY IN PRODUCTION.
i've updated meteor to the latest version, and I guess from that moment all I see when going in production is:

```
iron:router
Organize your Meteor application.

Router.route('/', function () {
  this.render('Home', {
    data: function () { return Items.findOne({_id: this.params._id}); }
  });
});
        
Check it out on Github:
https://github.com/eventedmind/iron-router 

And check out the new Guide:
https://eventedmind.github.io/iron-router
```

locally, with ```meteor```, everything works just fine.
when doing ```meteor --production``` or when deploying the application on the server, these message appears on the whole page.

any suggestions?

**Comment by cmather** [comment]
what do your server logs say?

**Comment by nick-preda** [comment]
no errors shown on the server side
the browser just shows the error page

**Comment by sungchi** [comment]
Similar error. Appears occasionally. Mainly seen only once to the person who first connected. (So hard to reproduce this bug)

http://deeplnk.com/c/XdKWYbFjnujL6QNjr
