### ISSUE TITLE
oops looks like there's no route on the client or the server for url shows only on iphone ?!

### ISSUE THREAD

**Issue by yanndebelgique** [iron-meteor/iron-router#1297]
Hello,

I have a problem with iron:router and iphone. When I go to lightnow.co on my computer every is fine but when I try to access it on my iphone I get the error :
     oops looks like there's no route on the client or the server for url

**Comment by rapsli** [comment]
same here. Could you figure out what it was?

**Comment by christieewen** [comment]
I'm having a similar issue using "meteor deploy".  The app works fine using localhost but when deployed to mysite.com or mysite.meteor.com I get the error: "oops looks like there's no route on the client".  I noticed in some cases, the deployment didn't happen although I didn't get any notice of errors.  I'm still trying to figure this out.  Did you have a code issue?

**Comment by rapsli** [comment]
It was the issue with the size. For some reason I had a really big asset in my public folder that bloated the whole app. Removing this fixed everything. The app is now only 4 MB, with that thing it was 50 MB

**Comment by yanndebelgique** [comment]
Wrap your initialization code in Meteor.startup
that solved my issues

**Comment by rapsli** [comment]
The question would only be: What would you consider the initialization code? The Router aswell?

**Comment by yanndebelgique** [comment]
Good point. I didn't need to wrap the router for it to work. You can always wrap it, probably safer.

**Comment by mgruen** [comment]
Same problem here - app works fine on localhost, and also works ok after initial authentication if I click on the existing nav links.  If I either refresh or try to go to a url manually, I hit the error.  This is on Chrome/Ubuntu (also happens on iphone).  It also happens if I close the browser and then return to the app - since it's sitll authenticated,  I get the route-not-exist error - and this time nothing works, not even clicking on the nav links.

**Comment by abhisheksoni27** [comment]
How can this be resolved?

**Comment by m52go** [comment]
I just hit this issue too. Added zero assets, only change to routes was adding 2 simple subscriptions, added 1 configureRoute setting (but commenting it out did nothing). Nothing else besides regular HTML/JS in the form of template helpers. 

Everything works as expected locally, but deploying to Meteor servers causes the "no route" message and zero functionality.

Very frustrating to have something break out of nowhere...I'll keep tinkering and report back what I find.

**Comment by prodogs** [comment]
Having same issue as everyone else - works fine locally but when deplolyed to modulus i get

Oops, looks like there's no route on the client or the server for url:

**Comment by zylootino** [comment]
I fixed the issue by fixing the errors showing in the browser console.

**Comment by panchiniak** [comment]
"there's no route" was showing even with no errors in the console. It vanished after meteor remove yogiben:admin.

**Comment by brewhk-dev** [comment]
Running `meteor update iron:middleware-stack` didn't work for us. We had to ensure all routes are named, that fixed the issue.

**Comment by filipblaauw** [comment]
For me it seemes that a seo package console warning was the issue. Removed the package that gave the warning (lookback seo), and the routes worked again on meteorapp.com.

lookback seo had this warning inside a test function: `Uncaught ReferenceError: Mongo is not defined` so I were not able to get rid of it.
