### ISSUE TITLE
Strange Router.current() behavior

### ISSUE THREAD

**Issue by zimt28** [iron-meteor/iron-router#1318]
When opening the console and running `Router.current().params` I get an empty array, but `Router.current().params._id` for example returns a correct id.

Here are more examples, I'd like to get number three running (all these are `Template.helpers`): 
```js
// 1. Doesn't work
pdf: function () {
  var params = Router.current().params;
  
  // Console Output:
  // []    
  console.log(params);
}


// 2. Works
pdf: function () {
  var id = Router.current().params._id;
  var n = Router.current().params.n;
  
  // Console Output:
  // C5hshvNHhddjhnvWq 0
  console.log(params, n);
}


// 3. Doesn't work
pdf: function () {
  var id = Router.current().params._id;
  var n = Router.current().params.n;
  
  var pdf = PDFs.findOne({
    patientId: id,
    quote: n
  });
    
  // Console Output:
  // undefined
  console.log(pdf)
}


// 4. Works
pdf: function () {

  // Values come from example 2
  var pdf = PDFs.findOne({
    patientId: 'C5hshvNHhddjhnvWq',
    quote: 0
  });
  
  // Console Output
  // > Object
  console.log(pdf);
}
```

Any suggestions?

**Comment by cmather** [comment]
`console.dir(Router.current().params)`

**Comment by cmather** [comment]
```javascript
console.dir(Router.current().params._id
```

apparently markdown doesn't work on the previous post :)

**Comment by zimt28** [comment]
Oh wow, that works! Could you explain why? `Array[0]` to me looks like it's an array that hasn't values but has some. Kind of :D

```[Log] Array[0]
_id: "C5hshvNHhddjhnvWq"
hash: null
length: 0
n: "0"
query: Object
__proto__: Array[0]
```

**Comment by cmather** [comment]
The params object is actually an array. But the array has properties on it just like any other object. So you could say myArray.prop = 'value' and then also work with the array using indices like myArray[0].

So why is params an array? So we can support anonymous wildcard parameters and put them someplace where you can reference them by index later.

Chrome doesn't let you inspect arrays as objects when you use console.log for some reason. But if you use console.dir it forces it into object form that you can drill into. Maybe you can find the more precise reason that is.

**Comment by zimt28** [comment]
Okay, thanks for your explanation!
I will close this now, as it's not a real issue.
