### ISSUE TITLE
onBeforeAction isn't being stacked on .extend

### ISSUE THREAD

**Issue by Firfi** [iron-meteor/iron-router#1328]
https://gist.github.com/Firfi/3c0950b57497bdc2a96e

error is `Error: Handler with name 'onBeforeAction' already exists.`, it appears only when I visit the route

**Comment by Firfi** [comment]
It seems to be an issue with es6. I just moved router.js to babel and es6.js extension. Maybe it handles .extends somehow differently (I still used the same function() syntax and no arrow syntax).

**Comment by Firfi** [comment]
Link to https://github.com/grigio/meteor-babel/issues/21

**Comment by grigio** [comment]
can you try to edit your `.meteor/packages` and put `grigio:babel` before all the packages?
