### ISSUE TITLE
Iron router and deeplinking

### ISSUE THREAD

**Issue by c316** [iron-meteor/iron-router#1330]
Mobile apps have a notion of deeplink routing which looks like this 

    mygreatapp://view?src=sourceHere

I have a cordova package (https://github.com/EddyVerbruggen/Custom-URL-scheme) which will setup the schema link for the mygreatapp:// association to the app, but once it passes the 
```
view?src=sourceHere
```

to the app I'd need to handle that portion myself. Problem is I can't figure out how to hook into the custom function that the docs say they provide and handle the route. 

Here is the function that receives the call to the app. It does log the link to the console and attempt to route, but this just shows a route not found page in the app. What might I be doing wrong here? 

```
Meteor.startup(function() {
    handleOpenURL = function handleOpenURL(url) {
        console.log("received url: " + url);
        var token = url.replace("mygreatapp://verify-email/", "");
        console.log("Token: " + token);
        Router.go('/verify-email/', {"paramToken": token});
    }
});
```

**Comment by c316** [comment]
What ended up working is not using the Router.go() command. Instead I used ```window.location.href = 'http://meteor.local/verify-email/' + token;``` like this

```
Meteor.startup(function() {
    handleOpenURL = function handleOpenURL(url) {
        var token = url.replace("mygreatapp://verify-email/", "");
        console.log("Token: " + token);
        window.location.href = 'http://meteor.local/verify-email/' + token;
    }
});
```

I'm not sure why the Router.go() command doesn't work if this command does work...

**Comment by zimme** [comment]
`Router.go('/verify-email/' + token);` should work, because then it's redirecting to that path and not looking for a defined route.

Another option is to define a route which handles the email verification instead if using the onVerificationLink thing. Then you can just do `Router.go('verifyEmail', {token: token});` to redirect to that route which handles the email verification in it's action function.
