### ISSUE TITLE
Question: singleton views / instances - re-render time on mobile.

### ISSUE THREAD

**Issue by ganySA** [iron-meteor/iron-router#1344]
Hi

A question i have regarding iron router and singleton views. I am currently building a mobile application  and to render views from scratch every time is not the way to go on mobile (Blaze just doesnt look great -rendering entire lists) on mobile. 

Is there any means in iron router to not "dispose" of a blaze view so that next time it doesnt re-render but simply brings it to the foreground... a singleton style approach? 

This type of performance is not very noticeable on desktops, but the minute you start loading lists of data on mobile from a "Master List -> Detail Page --> Master List" its very noticeable when going back to the master list which needs to be re-rendered and makes the application look incredibly slow vs native app.

The only way i seem to be getting around this is loading into yield areas on my main layout all my upfront, and then using router for smaller forms but manually doing all sorts of nasty stuff inside the action, like hide show divs on the big divs. Although this keeps the data in the dom permanently so ram consumption i assume would be higher the performance to view the data and not wait for Blaze render is night and day. Clicking between tabs for instance is instantaneous versus arriving at the tab then waiting for Blaze to start re-rendering :/ 

NB: This is not a subscription issue - waiting on subscriptions is not the problem. This is the inability of mobile devices to render items as well as browsers - laggy, gitters rendering ~ big images for about 50 items in a each loop.

**Comment by zimme** [comment]
One thing you can do is to have the different route's render the same template which renders all "templates" then have the different route's just hide/show different parts.

when iron:router sense that different routes renders the same template it doesn't re-render them but uses the one already rendered.

**Comment by ganySA** [comment]
Then you need to manually hide/show each one?

**Comment by zimme** [comment]
You can have parts of the template hide/show stuff based on a reactive-var which lives on the template instance and in each route which render the same template you can set that reactive-var to show the part of the template you want (this should also hide the other parts)

**Comment by chrisbutler** [comment]
more on this idea https://www.youtube.com/watch?v=0EF2PAUrVvQ
