### ISSUE TITLE
Iron Router, why don't you destroy and recreate my template?

### ISSUE THREAD

**Issue by satyavh** [iron-meteor/iron-router#1345]
I'm trying to implement template based subscriptions in order to have more (reactive) control over my subscriptions. Template based subscriptions must be defined Template.onCreated, and Template.onCreated only runs a single time when the template gets created.

So here's the route:
```
  @route 'collection/:id',
    action: ->
        @render 'posts'
    data: -> 
        @params.id
```

So based on data (@params.id) I'm setting up the subscription in Template.onCreated() (which works fine the first time).

Now lets navigate from `/collection/1` to `collection/2`. I'd expect the router to destroy the current view, reload the route, load a new dataset, render a new template. This kind of happens:

1. new data is set
2. the action hook runs again

But there are 2 things that do not happen:

1. the template.onDestroyed never gets called, which means the template doesn't get destroyed
2. the template.onCreated never gets called again, because the template was not destroyed. So no new template gets created.

Only when you move to a completely other route (like `/otherroute`) and come back to `/collection/2` does Iron Router destroy and recreate the template.

I don't know if this is by design, but it doesn't make much sense to me.  And it is really troublesome to work with, specially when doing template based subscriptions. 

Any suggestions?

**Comment by erasaur** [comment]
See https://github.com/iron-meteor/iron-router/issues/1337

**Comment by satyavh** [comment]
Thanks for pointing out. I was looking for something like this. I'll try the solutions in there.
