### ISSUE TITLE
Template.__create__ is undefined

### ISSUE THREAD

**Issue by Sebl29** [iron-meteor/iron-router#1349]
I am trying to get a tinytest working with meteor, in a package which is using iron:router. Everything else is working, only the test seems to miss a function.

meteor version: 1.1.0.2
iron:router version: 1.0.7

There is an error in my browser console:
"Uncaught TypeError: undefined is not a function".

In the debugger I focused on the line of layout.js:286 from iron:layout:

UI.registerHelper('yield', Template.__create__('yield', function () {
    var layout = findFirstLayout(this);

Here Template.__create__ is really undefined. So, this seems might be a bug, or?
Cheers,
 Sebl29

**Comment by robwatkin** [comment]
I'm new to tinytest and I've just bumped into this on too. I tried to mock it with the code below but I still get the error. I'll post to SO for some advice.

In package.js

    Package.onTest(function(api) {
      api.use('tinytest');
      api.addFiles('mocks.js');
      api.use('robwatkin:mypackage');
      api.addFiles('tests.js');
    });

in tests.js

    Tinytest.add('example', function (test) {
      test.equal(true, true);
    });

Gives

    Uncaught TypeError: Template.__create__ is not a function(anonymous function) @ layout.js:286(anonymous function) @ iron_layout.js?d62e492972d7f97328c54d2ba052d5adf0cf0d9a:534(anonymous function) @ iron_layout.js?  d62e492972d7f97328c54d2ba052d5adf0cf0d9a:541

**Comment by robwatkin** [comment]
It's happening in here  https://github.com/iron-meteor/iron-layout/blob/master/layout.js#L292

    UI.registerHelper('yield', new Template('yield', function () {
     var layout = findFirstLayout(this);

So I'll raise this over there.

**Comment by protometa** [comment]
Having the same issue.

**Comment by brettle** [comment]
Per my comment at iron-meteor/iron-layout#15, the fix is to specify at least version 1.0.0 in your `api.use` call, like this:

```javascript
api.use('iron:router@1.0.0`);
```
