### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by JulianNorton** [iron-meteor/iron-router#1350]
![screen shot 2015-05-19 at 11 51 32 am](https://cloud.githubusercontent.com/assets/2412992/7707392/85683760-fe1d-11e4-9c83-b180efe5017d.png)

https://eventedmind.github.io/iron-router

**Comment by JulianNorton** [comment]
pull request is here:
https://github.com/zicai/iron-router/commit/ab759c56c6da9226f2495740ade9081087bf0202

**Comment by cmather** [comment]
thks!
