### ISSUE TITLE
Router.go routes from 1.0.7 to 1.0.8 are not working

### ISSUE THREAD

**Issue by a-db** [iron-meteor/iron-router#1356]
I updated to 1.0.8 from 1.0.7 and all of my simple routes with Router.go('routeName', {_id: this._id}); do not work anymore. What has changed? The links all display /undefined and then the id. ex /test/undefined49asdfijoasdfi

**Comment by wallslide** [comment]
The cause is explained here https://github.com/iron-meteor/iron-url/issues/15 along with a pull request that should resolve the issue.

**Comment by a-db** [comment]
Thanks for heads up wallslide.

**Comment by cmather** [comment]
Oops I didn't take a close enough look at a pull request merge. I'll get out a new version first thing. Thanks for the patch.

**Comment by perak** [comment]
merge please!

**Comment by cmather** [comment]
should be fixed.

**Comment by a-db** [comment]
Confirmed thanks for the quick resolution.
