### ISSUE TITLE
pathFor with argument has "undefined" prefixed

### ISSUE THREAD

**Issue by Danilo-dk** [iron-meteor/iron-router#1357]
Ever since I updated iron:router to 1.0.8 I am getting undefined in my links. So where I previously had the id of a record as an argument, with this code:
```jade
a(href="{{pathFor 'scene' id=_id}}")
```
I am not getting the correct url, except for the undefined that's been introduced in the latest version. Instead of "/app/scenes/xxxxxx" I am getting "/app/scenes/undefinedxxxxxx".

Here's my route definition in case that may be the problem
````coffeescript
Router.route 'scene',
	data: ->
		cln_Scenarios.findOne @params.id
	path: 'app/scenes/:id'
	waitOn: ->
		Meteor.subscribe("singleOwnedScene", @params.id)
````

**Comment by David-Turbert** [comment]
same as you, also same problem on Router.go

**Comment by bobintornado** [comment]
+1

**Comment by jmlv** [comment]
+1

**Comment by yoh** [comment]
+1

**Comment by David-Turbert** [comment]
what are your latest packages updated ? 
for me (from):
iron:router                  1.0.7* 
meteorhacks:fast-render      2.4.0*
meteorhacks:kadira           2.20.6*
semantic:ui-css              1.12.2*
useraccounts:semantic-ui     1.10.0*

**Comment by Danilo-dk** [comment]
The only packages I updated were directly related to iron:router AFAIK.
My commit that had the update (and only the update) has these changes:

added:
iron:controller@1.0.7
iron:core@1.0.7
iron:dynamic-template@1.0.7
iron:layout@1.0.7
iron:location@1.0.7
iron:middleware-stack@1.0.7
iron:router@1.0.7
iron:url@1.0.7

removed:
iron:controller@1.0.8
iron:core@1.0.8
iron:dynamic-template@1.0.8
iron:layout@1.0.8
iron:location@1.0.8
iron:middleware-stack@1.0.8
iron:router@1.0.8
iron:url@1.0.8

**Comment by jmlv** [comment]
Similarly like @Danilo-dk

**Comment by n0ne** [comment]
https://github.com/iron-meteor/iron-router/issues/1356

**Comment by dionliddell** [comment]
Problem appears to be in url.js, the Url.prototype.resolve function.  
line 338 of url.js is:  return slash + format + escapedValue;
format isn't initialised anywhere so is always undefined.

**Comment by dj-foxxy** [comment]
+1

**Comment by sarasate** [comment]
+1

**Comment by tcastelli** [comment]
+1

**Comment by dubvfan87** [comment]
Anyone have a quick fix until we get an update?

**Comment by ababra** [comment]
+1

**Comment by cmather** [comment]
should be fixed

**Comment by ababra** [comment]
@cmather Thanks! Updating to 1.0.9 fixed the issue for me.

**Comment by jmlv** [comment]
Thanks!

**Comment by mattiLeBlanc** [comment]
many thanks....was debugging this and then realised I should google this issue :) Could have saved me an hour
