### ISSUE TITLE
issue with Router.go() after upgrade to 1.0.8 from 1.0.7

### ISSUE THREAD

**Issue by rb365** [iron-meteor/iron-router#1359]
updated iron router to 1.0.8 from 1.0.7 and get a problem:
I call Router.go('application', {_id: response}); in a call back of a Meteor method
where the definition for application route is: 
Router.route('/application/:_id', {
    name: 'application'
}
and response variable is response in callback from Meteor method

with 1.0.7 route goes properly to /application/2t6uD9ausB9MovToW
with 1.0.8 route goes incorrectly to /application/undefined2t6uD9ausB9MovToW

in 1.0.8 there is word 'undefined' added in front of the _id in the route

**Comment by cmather** [comment]
Update again to 1.0.9.

**Comment by rb365** [comment]
1.0.9 worked great, thanks!
