### ISSUE TITLE
Using router as HTTP proxy

### ISSUE THREAD

**Issue by yuvadm** [iron-meteor/iron-router#1366]
I have an edge case where some of my clients need to make a cross-domain request and in some edge cases I need to proxy this request through the server. The requests are static assets.

Is there any simple way to have the router proxy calls to `/proxy/foo/abc` to `http://example.com/foo/abc`? I am aware this might perform badly but at this point I just need to solve the edge cases for some of the clients.

**Comment by coopermaruyama** [comment]
I had this exact requirement and have it working perfectly using iron router. Here's the code for it, which would proxy requests made through app.com/proxy?url=myurl.com

```coffee
############################################################################/
##        Proxy Router                                                     /
##########################################################################/
# Proxy
Router.route("/proxy",
  where: "server"
).get(->
  url = Npm.require("url")
  self = this
  raw_url = url.parse(@request._parsedUrl).search.substr(1).match(/url\=[^\&]+/)[0].split("=")[1]
  the_url = decodeURIComponent raw_url
  the_url = if /^http\:\/\//.test(the_url) then the_url else "http://#{the_url}"
  console.log @request, raw_url, the_url
  Meteor.call "getURL", the_url, (err, response) ->
    try
      self.response.write(response.content)
      self.response.end()
    catch err
      console.log "Proxy failed when getting #{the_url}: #{err}"
      console.log "Response data for #{the_url}: #{response}"
)

```

**Comment by yuvadm** [comment]
@coopermaruyama that's awesome! Any idea how this performs in production?

**Comment by yuvadm** [comment]
Also, any idea how I can set a custom response header?

**Comment by coopermaruyama** [comment]
`@response.setHeader(name, value)`. You should have access to any of the methods outlined [here](https://nodejs.org/api/http.html#http_class_http_serverresponse).

So far for me I've had no problems in production. The only problem I see is that it's public so anyone can use your proxy. For some really basic security you can use `post` instead of `get` and require a token.

**Comment by coopermaruyama** [comment]
BTW in my method I use a meteor method because I'm injecting some stuff, but meteor has a built-in `HTTP.get` which you can use instead.

**Comment by yuvadm** [comment]
@coopermaruyama I only have one problem which is getting proper support for proxying binary content (images), but I think I have a solution for that. I'll go ahead and close this issue now, thanks for the help!
