### ISSUE TITLE
page refresh doesn't trigger onCreated and onRendered again

### ISSUE THREAD

**Issue by ayhanyildiz** [iron-meteor/iron-router#1376]
with first load of page onCreated or onRendered methods are triggered. But with page refresh they are skipped. without iron:router each refresh or first load triggers those methods. Is there work around or is this some kind of bug?

**Comment by chrisbutler** [comment]
@ayhanyildiz it seems like something else might be going on here. more details are needed

**Comment by ayhanyildiz** [comment]
this happens with api request. is there another templated methods others than onRendered, onCreated, onDestroyed? if visited with url it gets right but page refresh doesn't. Maybe meteor needs to answer what happens when page is refreshed.
