### ISSUE TITLE
Using inside package: cannot find template

### ISSUE THREAD

**Issue by sungwoncho** [iron-meteor/iron-router#1383]
I am using Iron Router inside a package, and it complains that it cannot find a template, even though I have defined it.

I get `Couldn't find a template named "layout" or "layout". Are you sure you defined it?`

I have defined a template called layout inside my package: `client/templates/shared/layout.html`

And I have required that file in package.js like this:

```
Package.onUse(function(api) {
  api.versionsFrom('1.1.0.2');

  api.use('iron:router@1.0.9');

  api.addFiles([
    'both/routes.js'
  ], ['client', 'server']);

  api.addFiles([
    'client/templates/shared/layout.html',
    'client/templates/home.html'
  ], 'client');
});
```

And I am using layout template in my route definition file, both/routes.js

```
Router.configure({
  layoutTemplate: 'layout'
});

Router.route('/', {
  name: 'home',
  template: 'home'
});
```

And in my main app, I am using this package. It can be found at .meteor/packages. Is this a bug?

**Comment by zimme** [comment]
You add `routes.js` file before the `layout.html` file so when the router looks for the layout template it hasn't been defined yet.

**Comment by sungwoncho** [comment]
@zimme The issue was not the load order. I needed to add `api.use('templating', 'client');` to get it working.

I see that iron router [already depends on `templating`.](https://github.com/iron-meteor/iron-router/blob/devel/package.js#L19). Perhaps adding `api.imply('templating', 'client')` will prevent problems of this sort in the future. Any thoughts?

**Comment by zimme** [comment]
I would think the load order was important too, but ok.

Yeah, implying `templating` would probably prevent this sort of issue in the future.
