### ISSUE TITLE
Route of "/" with no name fails autoname

### ISSUE THREAD

**Issue by cubitworx** [iron-meteor/iron-router#1388]
There is a bug where iron:router doesn't automatically create a name for a route if the route is "/". See project for complete reproduction.

    Router.route("/", {
        // name: "/",		// Uncomment this & it works
        ...
    });

Reproducible project here: https://github.com/cubitworx/iron-router-bug

**Comment by cubitworx** [comment]
Has this been read / Is anything happening on this? As far as I know I followed the required bug submission format & don't know if it has been received? It is a low level bug but even so a comment to acknowledge receipt of the problem would help, please. Thanks

**Comment by chrisbutler** [comment]
@cubitworx what should the name be? creating a template named "/" is probably a bad thing to encourage, no?

**Comment by cubitworx** [comment]
@chrisbutler I see that I didn't make the point clear. My apologies. The problem is not with the name but the fact that that specific route does not work without a name. I.e. give it a name & it works but leave the name out & it doesn't work. For all other routes it seems to work but not for "/" (index page)

**Comment by chrisbutler** [comment]
@cubitworx i understand what you're saying. but my point is that the reason it doesn't work is that ```/``` is not really a valid template name

the point of the autoname conversion is to create a name that works with ```Template.TemplateNameHere.helpers({})``` etc

you can see how the conversion works here: https://github.com/iron-meteor/iron-core/blob/master/lib/iron_core.js#L174
