### ISSUE TITLE
{{> yield}} is rendered after footer

### ISSUE THREAD

**Issue by achtan** [iron-meteor/iron-router#1395]
Hi, 
after redirecting with Router.go() content {{>yield}} is rendered after footer

my layout
````
<template name="baseLayout">
  {{> yield}}
  {{> footer}}
</template>
````

any idea how to fix this ?

PS: with {{pathFor ... }} all works OK

**Comment by abhiaiyer91** [comment]
What do you mean by redirecting with Router.go?

is this in the Router?

Could provide some sample code?

**Comment by achtan** [comment]
i ment: page re-render after calling Router.go()

currently i don have any example...

**Comment by Narven** [comment]
If you make
`
<template name="baseLayout">
  {{> yield 'main' }}
  {{> yield 'footer' }}
</template>
`
And use yieldTemplates, does it do the same thing?

**Comment by Narven** [comment]
That can also happen if your html is wrong.

**Comment by achtan** [comment]
hi, I moved to flow-router, so I just close this issue, thx for help
