### ISSUE TITLE
this.next is null

### ISSUE THREAD

**Issue by zachdixon** [iron-meteor/iron-router#1403]
I have a function inside an onBeforeAction hook that tries to log a user in if there's no currentUser and the correct cookies exist. Everything works fine but I'm having an issue with `this.next` being null. Since I'm doing an async call to a backend API to log in, I have a callback for when it returns in which I'm calling this.next, except no matter what I do, it's null. Does async not work in onBeforeAction hooks for some reason?

**Comment by nakhbari** [comment]
Yes i think there is documentation on this but onBeforeAction does not support async calls. I have worked around this by saving the this.next() at the beginning and then referencing it when the async callback is called.

**Comment by iSuslov** [comment]
+1. I have this in onRun

**Comment by zimme** [comment]
This should work?
```js
onBeforeAction: function() {
  var self = this;
  asyncCall(function(result) {
    console.log(result);
    self.next();
  });
}
```

**Comment by iSuslov** [comment]
@zimme I'm not aware of this :)
My problem is 
```
onRun: function(){
     var self = this; //self.next not null
     //some loop
     self.next() // null
}
```

if I assign exact next function, everything works

`var thisNext = this.next`

**Comment by zimme** [comment]
https://github.com/iron-meteor/iron-router/blob/devel/Guide.md#available-hook-methods

`this.next()` is only available in `onRerun`, `onBeforeAction`. So you can't really use a return value or wait for an async call in `onRun`, `onAfterAction` and `onStop`.

**Comment by iSuslov** [comment]
@zimme Thank you. I was thinking that I've read the documentation and somehow saw that this.next() applicable for onRun
