### ISSUE TITLE
Unwanted ad-ware in my project

### ISSUE THREAD

**Issue by yanickrochon** [iron-meteor/iron-router#1407]
Why is this rendered in my project ?

![selection_025](https://cloud.githubusercontent.com/assets/78461/8892295/11335230-331f-11e5-9bbb-95c9a06d791e.png)

This is coming from the sources

![selection_026](https://cloud.githubusercontent.com/assets/78461/8892296/1d29bce6-331f-11e5-8b07-03e76ccbf91b.png)

I want to remove this unwanted piece of HTML on the footer of my pages, how do I do that?

**Comment by NicolasParada** [comment]
Of course you get this after install iron:router.
Do what it say there. It's just a minitutorial.

**Comment by yanickrochon** [comment]
The package was installed as a dependency for `useraccounts:semantic-ui`. Anyhow, I find this somehow intrusive and should allow to be discarded.

**Comment by vimes1984** [comment]
This is a free package... I don't even maintain it and I find it slightly offensive if your qualming about someone offering you a free software with the capability of removing this whenever you want..

**Comment by yanickrochon** [comment]
@vimes1984 there are ways to inform the user about what he/she should do next. For instance, the `console` is a **great** way of doing it. Inserting HTML onto the user's page, forcing him/her to configure a third party package (as I said, it was installed as a dependency to another package, I did **not** install this) *is* intrusive.

And all this however popular this module or how free it can be.

**Comment by benmgreene** [comment]
You did install it.  The fact that you did not understand the dependencies of a package, and therefore did not *know* that you installed it, does not strengthen your position.

If you are not in favor of Iron Router’s method of communication, I’m sure a pull request would be welcome.  If it is not accepted, you’ll no doubt have the opportunity to use alternative packages.

Let’s close this thread.

**Comment by yanickrochon** [comment]
The "how" this package was installed is irrelevant. The mean of communication is intrusive, and I have been saying this all along.

I'll close this thread, as I seem to be in minority with this.

**Comment by uriva** [comment]
Quite obviously this has to go.
This is even annoying when installing iron:router itself.

**Comment by vimes1984** [comment]
I don't use Iron-router ( I prefer to use angular-ui), but I still don't think this is an issue in the slightest. Documentation is lacking all over Meteor projects as a norm and given how often  this particular package is used I think it's nice to have that right there in your face the moment it's installed...

**Comment by yanickrochon** [comment]
@vimes1984 as I was saying; there are different ways to document something. And, since we're using JavaScript, we have `console.warn` as a better way to communicate things instead of injecting stuff as HTML. The issue is not about *not* documenting something, but about doing a better job at it... especially, as stated, when the module is installed as part of a third party install.

Because, as of it is right now, it is unprofessional and intrusive.
