### ISSUE TITLE
Server side route: Error: request aborted (on POST Webhook)

### ISSUE THREAD

**Issue by thomasf1** [iron-meteor/iron-router#1409]
We´re trying to get Mailgun webhooks working - some work, but the ones using "application/x-www-form-urlencoded" seem to result in a timeout and then an error.

Our setup:
Mailgun receives a incoming email and triggers a webhook on our server which we stripped down to the bare minimum:

```coffeescript
Router.route("/webhooks/mailgun", {where: 'server'}).post ->
  console.log "*** /webhooks/mailgun"
```

Then, our server trows this error: (no console.log):
```
[rentkitbeta.cloudapp.net] Error: request aborted
[rentkitbeta.cloudapp.net]     at makeError (/bundle/bundle/programs/server/npm/iron_router/node_modules/body-parser/node_modules/raw-body/index.js:154:15)
[rentkitbeta.cloudapp.net]     at IncomingMessage.onAborted (/bundle/bundle/programs/server/npm/iron_router/node_modules/body-parser/node_modules/raw-body/index.js:252:10)
[rentkitbeta.cloudapp.net]     at IncomingMessage.emit (events.js:92:17)
[rentkitbeta.cloudapp.net]     at abortIncoming (http.js:1916:11)
[rentkitbeta.cloudapp.net]     at Socket.serverSocketCloseListener (http.js:1928:5)
[rentkitbeta.cloudapp.net]     at Socket.emit (events.js:117:20)
[rentkitbeta.cloudapp.net]     at TCP.close (net.js:466:12)
```

And Mailgun reports a "502 Bad Gateway" error on the webhook and schedules it to try again.

One noteable thing is a maybe 30-60 second lag from Mailgun getting the message to the Error being thrown, maybe pointing towards some sort of timeout / missing data.

We´re not quite sure how to further debug it at the moment...

**Comment by thomasf1** [comment]
Ah, found the cause of the issue... Another Package was interfering.

**Comment by heckler078** [comment]
Hey thomasf1

Any more details on which package was interfering? I am running across an identical problem.

**Comment by thomasf1** [comment]
Hey... It was a custom Busboy-based package we´ve used to enable attachments on POST requests...

**Comment by heckler078** [comment]
hmm it's something else for me then. But thanks for chiming in!

**Comment by thomasf1** [comment]
Sure... It was really annoying to debug as there where no clear error messages... The way we found it was to see that GET requests worked and what the difference between working and dying POST requests was...

**Comment by heckler078** [comment]
Yeah I figure it must me something dumb since the Mailgun "Send A Sample POST" works just fine, but when I try to route an incoming email it times out and I get a similar error in the app log. Annoying...

**Comment by thomasf1** [comment]
@heckler078 The content type between the Mailgun Sample POST and the actual webhook can be different (and was in our case)... We used a http://requestb.in/ to debug it.

**Comment by heckler078** [comment]
That could be it!

Sample POST to RequestBin url:
Content-Type: multipart/form-data; boundary=7cb28e48-a645-4c5e-a998-dc4f9aa3fe4f

Email Route (forward to RequestBin url):
Content-Type: application/x-www-form-urlencoded


Did you solve this at the iron:router code level or is there a way to somehow force Mailgun to create those POST requests differently?

Btw, thanks again for chiming in, I really appreciate it!

**Comment by thomasf1** [comment]
It actually worked with pure iron router... We´ve re-created the request (raw postbin + headers) with postman and tested locally. Pure Iron router worked, then we added all the other packages back...

**Comment by heckler078** [comment]
Hah... you just solved it for me!

I thought using busboy was needed because iron router can't handle multipart requests. I came across this consistently in a few writeups I've seen.

I just got rid of busboy logic and now the email works and Sample Post doesn't. Bizarre. I wish I understood better what's going on at a lower level.

**Comment by thomasf1** [comment]
Great :)... You´re welcome!

**Comment by heckler078** [comment]
Yup, you're awesome thanks again! I mean now the route breaks if there is an attachment in the email, but at least I see what's going on and can try dealing with it.

**Comment by Gervwyk** [comment]
how did you resolve dealing with attachments?
I dont really care to save the attachments, just want to be able to save the sender details.

**Comment by heckler078** [comment]
I ended up switching to Postmark so I don't remember how far I got with Mailgun. Postmark just worked out of the box.

**Comment by mayank-purohit** [comment]
Using webhook for delivery of email but mailgun sends 502 Bad Gateway, The server returned an invalid or incomplete response.Is it async in nature or something else
