### ISSUE TITLE
Handling static files download

### ISSUE THREAD

**Issue by piffie** [iron-meteor/iron-router#141]
Hi,

needed to link to static files on the server....

this is what i come up with

``` coffescript
@route 'files', {path: '/files/*'},-> window.location.href = window.location.href
```

Or does someone has a better idea?

**Comment by francisbyrne** [comment]
@cmather I'm still a bit confused about this. I just want to host a static file from `public` folder e.g. `public/images/logo.png` for download.

For a regular website, I'd just use:

```html
<a href="images/logo.png" download="logo">download me</a>
```

But when I try this in Iron Router, I just get a redirect to the image file itself.

The solution in your previous post seems like something for dynamically creating a file on the server but I just want to serve a regular static file, so is there something a little simpler than creating the server route and manually serving a server response? Maybe I am missing something here.
