### ISSUE TITLE
Javascript on Template Rendering

### ISSUE THREAD

**Issue by icodemachine** [iron-meteor/iron-router#1429]
Javascript files execute before the template actually renders. So, styling related javascript isn't rendered properly. Need a workaround for this.

**Comment by mikeifomin** [comment]
@icodemachine did you try to style html code with template helpers?

```html
<template name="bar">
	<div calss="progress-bar" style="width:{{width}}%"></div>
</template>
```

```javascript

Template.bar.helpers({
    
    width:function(){
        
        // some reactive source
        var width = Session.get('currentProgress') || 0;
        
        return width
    }
})

```

Meteor way is to use reactivity everywhere. 

But if you need pure jQuery DOM manipulation use  [template.onRendered](http://docs.meteor.com/#/full/template_onRendered) method.

See more  [Using Meteor’s Rendered Callback](http://blog.benmcmahen.com/post/44771047946/using-meteors-rendered-callback)
