### ISSUE TITLE
Persistent "Organize your Meteor application." message

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [iron-meteor/iron-router#1430]
Hi, I downloaded a boilerplate from INSPINIA Admin template
https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S
It uses iron router for default, but I want to use Flow Router
I removed iron:router and other dependants and added flow routes packages.
Flow router is working, but in the end of the page, meteor is always displaying the "Organize your meteor application" message from iron router

How can I remove this ?

Im using Meteor 1.2

**Comment by Narven** [comment]
If not mistaken iron router gives that error when something is wrong with a template.

Can you check: https://github.com/iron-meteor/iron-router/issues/996

**Comment by XavaDigital** [comment]
I recently had this problem, and realised that Iron Router was being pulled in as a dependency by another plugin. In my case it was ms-seo. 

There may well be other plugins that also pull Iron router in even when you've removed it from your explicitly added packages. The console messages may give you a clue.
