### ISSUE TITLE
doesn't work well with file input from material design

### ISSUE THREAD

**Issue by viveksd87** [iron-meteor/iron-router#1431]
I am using the official meteor package for material design in one of my projects.

I tried rendering a template with a form that needed a "file" as input.

When I tried rendering without using route, the file-path was visible.
But when I tried rendering via route, the file-path is not visible.

Is this a known issue? Any workarounds?

For reference, this is the example I tried out:
http://materializecss.com/forms.html#file

**Comment by macrozone** [comment]
it seems not related to iron:router as iron:router has nothing to do with forms. You may provide us a test-repository or some code-snippets.

**Comment by viveksd87** [comment]
I didn't mean it just for forms, but it seems to be the problem with any page that needs some dynamic behavior using js/jquery. Even using Meteor.template.rendered didn't help the cause.

I believe it has got something to do with rendering. Not sure if the issue is with the blaze rendering engine or the router, hence posted it here. One of the reasons I thought could be that, I am trying to manipulate/change the dom here after the template is rendered, and that might not be supported currently. But I am not sure.

However for the time being I actually got it working by inserting an explicit jquery within the html template itself, to simulate the same behavior as that of material js.

It looked like this:

$('.file-field').each(function() {
                var path_input = $(this).find('input.file-path');
                $(this).find('input[type="file"]').change(function () {
                    console.log($(this)[0].files[0].name);
                    path_input.val($(this)[0].files[0].name);
                    path_input.trigger('change');
                });
            });
