### ISSUE TITLE
onStop not working on designed 

### ISSUE THREAD

**Issue by almogdesign** [iron-meteor/iron-router#1437]
My understanding from "onStop: Called when the route is stopped, typically right before a new route is run." is that when calling the onStop hook the router should stop and not load the new router however when I test it out it's loading the new route? 
```javascript
Router.route('createPost', {
    layoutTemplate: 'layoutApp',
    path: '/create-post',
    waitOn: function(){
        return [Meteor.subscribe('currentUser'), Meteor.subscribe('postsImages')];
    },
    onStop:function(){
        bootbox.confirm("Are you sure?", function(result) {
            console.log(result);
            //Example.show("Confirm result: "+result);
        });
    }
}); 
```

**Comment by macrozone** [comment]
onStop is called when the route is stopped, but there is no api there to prevent the router to actually stop the router. It works as documented.

You maybe could use a global onBeforeAction-hook and check if a user navigates away and ask for confirmation. But you would need to restore the previous url. I am also not sure if the router destroys the layout of the old page before calling the onBeforeAction-hook of the next route.
