### ISSUE TITLE
ReferenceError: EJSON is not defined

### ISSUE THREAD

**Issue by HolgerM78** [iron-meteor/iron-router#1438]
When creating a new Meteor (v1.2.0.1) app and adding iron:router, there seems to be a problem with configuring a layoutTemplate like so:

Router.configure({
  layoutTemplate: 'defaultLayout'
});

On the client-side I get the following error:
Exception in callback of async function: ReferenceError: EJSON is not defined

I could fix it by adding the ejson package, so I guess there is a dependency missing?
Can anyone reproduce this?

**Comment by cylauj** [comment]
I have the same issue. I've created a brand new app and added iron:router. Got the exact same error on the client, and resolved with a simple 'meteor add ejson'.

**Comment by Multiply** [comment]
I had the same error when updating iron-router-progress. Can confirm `meteor add ejson` fixes it.

**Comment by lnmunhoz** [comment]
@HolgerM78 Just run `meteor add ejson` as @cylauj and @Multiply said :+1:

**Comment by aldeed** [comment]
+1

The proper fix is to add `api.use('ejson')` here: https://github.com/iron-meteor/iron-middleware-stack/blob/master/package.js

**Comment by tro3** [comment]
+1

**Comment by mizzao** [comment]
related to missing `api.use('tracker')` as reported in iron-meteor/iron-layout#18

**Comment by rfox90** [comment]
Pull request for ejson problem made here https://github.com/iron-meteor/iron-router/issues/1438

**Comment by ghirlekar** [comment]
```meteor add ejson``` worked perfectly for me too

**Comment by chrisbutler** [comment]
@HolgerM78 @cylauj @Multiply @lnmunhoz @aldeed @tro3 @mizzao @ghirlekar fixed in 1.0.10
