### ISSUE TITLE
Iron Router and Meteor 1.2

### ISSUE THREAD

**Issue by rfox90** [iron-meteor/iron-router#1443]
This issue actually relates to the middleware-stack repo but I thought it might get more response here. Due to contributor watch statuses.

Meteor 1.2 now requires users to declare a few package dependencies explicitly. One of these is ejson which the middleware stack relies on.

There's a PR here: https://github.com/iron-meteor/iron-middleware-stack/pull/7 to fix the issue.

And a ton of discussion here: https://forums.meteor.com/t/iron-router-not-working-with-meteor-1-2/10196

Could someone take a look please?

I'd like to avoid emailing contributors directly.

**Comment by ajoachin2** [comment]
Thank you for the links that you provided....they give a satisfactory fix to the issue which I am sure will be resolved soon....I asked a similar question on the post before this one. Thanks again.

**Comment by SachaG** [comment]
Would love to know if this is going to be added to IR as a dependency, or if we should update Discover Meteor to tell people to manually add the EJSON package.

**Comment by dotnetwise** [comment]
+1

**Comment by chrisbutler** [comment]
@rfox90 @ajoachin2 @SachaG @dotnetwise fixed in 1.0.10

**Comment by rfox90** [comment]
Huge thanks!

:+1:
