### ISSUE TITLE
onBeforeAction except doesn't recognize my route with an argument

### ISSUE THREAD

**Issue by ibussieres** [iron-meteor/iron-router#1444]
Router.route('/', function () {
      this.render('Home');
    });
    
    Router.route('/signin');
    Router.route('/signup');
    Router.route('/signup/:token', {
      template: 'signup',
      data: function() {
        Session.set('token', this.params.token);
      }
    });
    Router.route('/users');
    
    var isSignedIn = function () {
      if (!(Meteor.user() || Meteor.loggingIn())) {
        Router.go('signin');
      } else {
        this.next();
      }
    };
    
    Router.onBeforeAction(isSignedIn, {except: ['signin', 'signup', 'signup/:token']});

Navigating to `/signup/whatevertoken` still triggers isSignedIn, `/signup` does not. Am I doing it wrong?

**Comment by ibussieres** [comment]
Wow. Just figured it our by adding a debugger un my hook function and calling `Router.current().route.getName()`. Turns out the route is referred to as `signup.:token`. Will try to get round to a PR that adds this to the docs.

**Comment by zimme** [comment]
You could just name your routes manually using `name: 'name'` in the route options and you just use that name to refer to your route.

**Comment by chrisbutler** [comment]
+1 for @zimme's suggestion, though we could clarify this in this part of the guide http://iron-meteor.github.io/iron-router/#named-routes
