### ISSUE TITLE
Reactive dict (state) does not allow objects with functions

### ISSUE THREAD

**Issue by iSuslov** [iron-meteor/iron-router#1445]
If you put in `state` an object with function inside, function will disappear.

```
waitOn: function(){
   this.state.set('object', {a:3, b: function(){} });
  //....
} 

```
    "buttons":function(){
		var obj = Iron.controller().state.get('object');
		console.log(obj) // outputs {a:3}
	},

**Comment by fabyeah** [comment]
I believe this is an issue with Meteor, not iron-router.
ReactiveDicts (like Session variables), may only hold EJSON data, which functions are not.

http://docs.meteor.com/#/full/session
http://docs.meteor.com/#/full/ejson
