### ISSUE TITLE
ReferenceError: AppController is not defined

### ISSUE THREAD

**Issue by wiserweb** [iron-meteor/iron-router#1446]
Issue:
If you use a class name (and filename) that is alphabetically after AppController you will get the "ReferenceError: AppController is not defined".

For example consider the class call AddressController. It will cause the error.

AddressController = AppController.extend({
    waitOn: function() {
        return this.subscribe('tasks');
    },
    data: {
        tasks: Tasks.find({})
    },
    onAfterAction: function () {
        Meta.setTitle('Address');
    }
});

AddressController.events({
    'click [data-action=doSomething]': function (event, template) {
        event.preventDefault();
    }
});

Exception "ReferenceError: AppController is not defined"

Workaround:
Renaming the class and the file from /both/app/address.js to /both/app/caddress.js fixes the issue. If the class is rename without renaming the file the error still occurs.

CAddressController = AppController.extend({
    waitOn: function() {
        return this.subscribe('tasks');
    },
    data: {
        tasks: Tasks.find({})
    },
    onAfterAction: function () {
        Meta.setTitle('Address');
    }
});

CAddressController.events({
    'click [data-action=doSomething]': function (event, template) {
        event.preventDefault();
    }
});

This might have something to do with the autoloader logic.

References:
http://stackoverflow.com/questions/28385026/iron-router-referenceerror-appcontroller-is-not-defined

**Comment by chrisbutler** [comment]
this is related to the order in which meteor concatenates js files
