### ISSUE TITLE
this.params.name not defined inside onBeforeAction

### ISSUE THREAD

**Issue by PolGuixe** [iron-meteor/iron-router#1474]
```this.params.name``` used to return the template name in: 
```
Router.onBeforeAction(function () {
  if (Meteor.userId()) {
    if (this.params.name == 'landingPage') {
      Router.go('/map');
      this.next();
    } else {
      this.next();
    }
  } else {
    Router.go('/');
    this.next();
  }
}, {
  except: ['signin']
});

```

However now is undefined

**Comment by PolGuixe** [comment]
Work around using ```Router.current().route.getName()```altough I don't know if it's the best way.

**Comment by chrisbutler** [comment]
@PolGuixe when you say used to, do you mean with an older version of IR? `getName()` is actually the correct way to do it

**Comment by PolGuixe** [comment]
But should `this.params.getName()` work?

**Comment by chrisbutler** [comment]
per the guide (http://iron-meteor.github.io/iron-router/#getting-the-current-route) it should not

`this.params` is for accessing parts of the url. the name of the route doesn't fall into that category

**Comment by PolGuixe** [comment]
Understood. 

Many thanks,
