### ISSUE TITLE
Used from in an Package? Errors result

### ISSUE THREAD

**Issue by MasterJames** [iron-meteor/iron-router#1475]
I was attempting a very basic initial test from inside a 'Package' (not the main Meteor app but a Custom Package inside the 'packages' folder via...

     api.use(['templating', 'iron:router'], ['client', 'server']);
or
     api.use(['templating', 'iron:router']);

and it reports various errors basically...

     Template.__create__ is not a function
     Iron.Layout is not a function
     Uncaught TypeError: Cannot read property 'RouteController' of undefined

Is there any simple way to see this work from a Package?

I added it into the main meteor package and without the api.use etc., still no dice.

**Comment by chrisbutler** [comment]
does adding `api.imply('templating')` make a difference?

**Comment by MasterJames** [comment]
Thanks for the suggestion I learned something deeper looking into that.
It seems the best answer to my problem, (with running Iron Router from a package,) in a later low level rebuild use-case test was this comment about forcing a current version.

```
  api.use(['iron:router@1.0.12', 'iron:layout@1.0.12']);
```

https://github.com/iron-meteor/iron-layout/issues/15#issuecomment-130536731

**Comment by chrisbutler** [comment]
:+1:
