### ISSUE TITLE
Controller Executing : 2 times :  subscriptions function called twice?

### ISSUE THREAD

**Issue by anupnitkkr** [iron-meteor/iron-router#1485]
FeedbackController = RouteController.extend({
  layoutTemplate: 'MasterLayout',

  subscriptions: function() {
      var hotelObject  =  gaHelper.getData("hotelObject");
      var user =  gaHelper.getData('user');  
        console.log('Meteor feedback call')
        Meteor.call('feedbackdetails_updated',user,hotelObject);
  },

  action: function() {
    this.render('Feedback');
  }
});

**Comment by chrisbutler** [comment]
@anupnitkkr subscriptions is reactive, so you really don't want to call a meteor method there. that's likely causing the function to re-run
