### ISSUE TITLE
Inadequte error checking with Router.current().route.getName()

### ISSUE THREAD

**Issue by TimeBandit** [iron-meteor/iron-router#1491]
I misspelled the end of the above named chained methods as Router.current().route.get**n**ame() and no error was returned.

**Comment by chrisbutler** [comment]
the standard "not a function" error is returned in JS

**Comment by TimeBandit** [comment]
When the method is spelled incorrectly, meteor console successfully refreshes without any errors. The only piece of info pointing to the error could be found in a nondescript message in the browser console.
'''
Exception in template helper: @http://localhost:3000/app/client/templates/layout/layout.js?96edb87952eeb2cc3173ca326b6bdfbb6dc50bad:10:24
'''
I think the meteor refresh should at least fail, but then maybe it more of a meteor issue than iron-router but the main issue is no error was flagged in the meteor console.
