### ISSUE TITLE
How are routes registered only server-side still invoked from the client?

### ISSUE THREAD

**Issue by GeorgeCalvert** [iron-meteor/iron-router#1496]
I have client-side routes for the app and server-side routes for a REST API (required for systems integration).  The routes are declared in environment-specific code: client-side routes via code in `client` directories and the corresponding for server-side, with each explicitly setting the `where` option accordingly.

When I change the URL on the client (by clicking a link), Router not only runs that route on the client -- it also invokes the server to dispatch into its middleware stack.  I get this behavior can be useful, but there are plenty of routes where I don't want to serve anything.

**How/where does one disable this behavior?** Adding server-side handlers that punt with `next()` either runs afoul of a 404 catchall or (avoiding that) just hangs until the client times out.  And of course sending a response blows out the template the client-side rendered. 

**Does anyone else have this as an issue?** As a relative newb to Iron:Router and Meteor world, perhaps I'm conceiving of the architecture incorrectly.

**Comment by chrisbutler** [comment]
@GeorgeCalvert i believe all of your routes should be in a directory that is shared between client & server

**Comment by GeorgeCalvert** [comment]
@chrisbutler, thanks, but how does that address the core issue?  A client-side URL change dispatches _both_ client- and server-side.  The client then waits for the server-side route to respond and any response will spoil the template the client-side rendered.
