### ISSUE TITLE
yield template not rendered in IE9

### ISSUE THREAD

**Issue by Twisterking** [iron-meteor/iron-router#1507]
Currently working on an app which should also run on older browsers (stupid big enterprises still use that old stuff) ...
In IE10 and 11 everything is fine but in IE9 a stange error occurs. The fallback to "hash urls" (because of not supported pushState) works just fine but yield templates such as my header are not loaded.
No errors in console. The weirdest part is that **after opening the IE debugger/console at least once the yield template is loaded**! I can even close the console again and do a hard-refresh (actually reloading the page) and the header is properly displayed.
Any ideas on this?

**Comment by chrisbutler** [comment]
@Twisterking you probably have some `console.log` statements somewhere. In IE 9, `console` is undefined unless the developer tools have been loaded

**Comment by Twisterking** [comment]
Oh wow never heard of that. Thanks for that input!
So I **can not** have any `console.log` statements in my whole meteor client code to run it properly on IE9?!

**Comment by chrisbutler** [comment]
there are a few ways to handle it, see http://stackoverflow.com/questions/3326650/console-is-undefined-error-for-internet-explorer for a good variety
