### ISSUE TITLE
How can I return the process.env variable?

### ISSUE THREAD

**Issue by dotku** [iron-meteor/iron-router#1510]
I'm trying to retrive the data in process.env by this

```
Router.route('/env', {
  data: {
    env: process.env.METEOR_ENV
  }
});
```

and I got error liket this:

> Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/env."

**Comment by zenonn37** [comment]
It should be Router.route

**Comment by dotku** [comment]
@zenonn37 I also tried server side

```
Router.route('/env', function () {
  var req = this.request;
  var res = this.response;
  res.end(process.env);
}, {where: 'server'});
```

I got error

> TypeError: Argument must be a string at getSize (C:\Users\lwj\AppData\Local.meteor\packages\webapp\1.2.3\npm\node_modules\connect\lib\middleware\compress.js:188:14) at ServerResponse.res.end (C:\Users\lwj\AppData\Local.meteor\packages\webapp\1.2.3\npm\node_modules\connect\lib\middleware\compress.js:115:33) at [object Object].Router.route.where (server/app.js:5:7) at boundNext (packages/iron_middleware-stack/lib/middleware_stack.js:251:1) at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1) at packages/meteor/dynamics_nodejs.js:123:1 at [object Object].urlencodedParser (C:\Users\lwj\AppData\Local.meteor\packages\iron_router\1.0.12\npm\node_modules\body-parser\lib\types\urlencoded.js:84:40) at packages/iron_router/lib/router.js:277:1 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) at [object Object].hookWithOptions (packages/iron_router/lib/router.js:276:1)

**Comment by ecwyne** [comment]
`process.env` is an object, not a a string

``` javascript
res.end(JSON.stringify(process.env));
```
