### ISSUE TITLE
waitOn issue

### ISSUE THREAD

**Issue by KovacicB** [iron-meteor/iron-router#1512]
Hey, 

I'm working on my meteor project for quite some time now and I've been trying to avoid manual publish and subscribe calls by using autopublish package but I now see that I can't really use that since I need to wait for data to load before rendering templates. We've already used waitOn in a yet unfinished meteor app we were working on in the beginnning of the last year but it doesn't seem to work in my project.

In routes.js file I have:

``` javascript
RouterLayer.route('/home/:_id', {
    name: 'home',
    template: 'home_index',
    waitOn: WaitForData
});
...
function WaitForData() {
    return [Meteor.subscribe("customers"),
      Meteor.subscribe("diseaseGroups"),
      Meteor.subscribe("diseases"),
      Meteor.subscribe("roles"),
      Meteor.subscribe("symptoms"),
      Meteor.subscribe("users")];
}
```

but I get the error saying: "Match error: Unknown key in field waitOn". Any ideas?

Thanks in advance

**Comment by chrisbutler** [comment]
i think your declaration syntax is the issue... can you change it to `var WaitForData = function() {}` and see if that makes a difference?

**Comment by KovacicB** [comment]
<img width="1284" alt="screenshot 2016-02-17 23 53 52" src="https://cloud.githubusercontent.com/assets/10382356/13127817/dc014e9a-d5d1-11e5-8150-d38aeb783904.png">

Nope, not working..anything else?
