### ISSUE TITLE
MiddlewareStack duplicate handler issue on Microsoft Edge & Chrome Canary

### ISSUE THREAD

**Issue by nathan-muir** [iron-meteor/iron-router#1513]
@tmeasday Not sure if you're still maintaining this. This is kind of related to #986 which you commented on. Also relates to #1270, and #1328.

[This example](https://gist.github.com/nathan-muir/c79ec2e7a730cb688954) now fails in the Microsoft Edge browser. (& Also in Chrome Canary w/ Experimental Javascript On.)

**Why:**
Because `MiddlewareStack` does some funky things with function names and uniqueness.

In Microsoft Edge, we now have new behaviour with function names & object literals:

``` js
var myObj = {
  // Note, function is anonymous.
  onBeforeAction: function() {} 
};
console.log(myObj.onBeforeAction.name)
// in Chrome/Firefox: ""
// in Edge: "onBeforeAction"
// in Chrome Canary + Experimental Javascript: "onBeforeAction"
```

That's right, _anonymous_ functions now get names in object literals, even without using es6 object syntax.

**How:**
1. [Because `MiddlewareStack._create` enforces a 'unique' mapping of `Handler`'s names.](https://github.com/iron-meteor/iron-middleware-stack/blob/master/lib/middleware_stack.js#L29)
2. [`Handler` automatically "picks" a name for any-named function](https://github.com/iron-meteor/iron-middleware-stack/blob/master/lib/handler.js#L49)

**Proposed Solution:**

I can't find any code in `iron-router` that even uses any of the name-related API's. (`findByName`, `insertBefore` and `insertAfter`).

So there are really two options:
1. Add some option / flag / type that bypasses names in `MiddlewareStack`. (Maintaining existing API's if someone is using it?)
2. Just remove anything `name` related from `MiddlewareStack`, and bump a major version. [Pull Request](https://github.com/iron-meteor/iron-middleware-stack/pull/8)

**Comment by MiroHibler** [comment]
I can confirm this is also happening in the latest version of Chrome Canary (currently v50.0.2653.0 but it started in v50.0.2651.0 I believe).

**Comment by nathan-muir** [comment]
Thanks @MiroHibler, I could reproduce in Chrome Canary too, but only after enabling "
Experimental Javascript" in chrome://flags/#enable-javascript-harmony

**Comment by chrisbutler** [comment]
@nathan-muir is this definitely the fix? https://github.com/iron-meteor/iron-middleware-stack/pull/8

**Comment by nathan-muir** [comment]
@chrisbutler It's _a_ fix (I've currently deployed for my apps); 

Use at your own discretion, `iron-router` is a bit of a tangle though (to me), so I'm hoping to get someone more knowledgeable to review.

**Comment by tmeasday** [comment]
Hi @nathan-muir -- I am not maintaining IR at this point. I'm not sure what the current status of maintenance is. @cmather?

**Comment by sylido** [comment]
I can verify this behavior on Version 51.0.2669.0 canary (64-bit) without touching the default setting for Experimental Javascript (disabled). Removing the second onBeforeAction hook fixes the problem.

**Comment by lorensr** [comment]
Looks related: #1520 

I do have multiple global `onBeforeAction`s, if that's the problem

**Comment by nathan-muir** [comment]
@lorensr yeah, that would be it

**Comment by mmdclx** [comment]
Receiving this error in Chrome canary 51.0.2673.0:

`middleware_stack.js:31 Uncaught Error: Handler with name 'route' already exists.` 

From a simple:

```
Router.route('/aroute', function() {});
```

Until @nathan-muir's code is reviewed and pulled into main repo, the error can be subdued by forcing each route to be named:

```
Router.route('/aroute', {name: 'aroute'}, function() {});
```

**Comment by maxfi** [comment]
Thanks @zlot. That's fixed it for me on Chrome Canary 51.0.2673.0 (64-bit) as well.

**Comment by tmeasday** [comment]
Fixed: `meteor update iron:middleware-stack`.

**Comment by markreid** [comment]
I understand there's a resolution for this but it may be worth noting that it's impacting Chrome 51.x which is now stable.

**Comment by brewhk-dev** [comment]
Running `meteor update iron:middleware-stack` didn't work for us. Instead, we had to ensure all routes  are [named](http://iron-meteor.github.io/iron-router/#named-routes) - that fixed it.

**Comment by tmeasday** [comment]
@brewhk-dev what version of I:ms did you end up with?

**Comment by tmeasday** [comment]
I suspect I need to do a release of iron router that explicitly depends on this fixed version.

**Comment by brewhk-dev** [comment]
Our app is running on METEOR@1.1.0.2, with the follow `iron:*` versions:

```
iron:controller@1.0.8
iron:core@1.0.11
iron:dynamic-template@1.0.8
iron:layout@1.0.8
iron:location@1.0.9
iron:middleware-stack@1.1.0
iron:router@1.0.9
iron:url@1.0.11
```

Chrome version - 51.0.2704.84 (64-bit)

But simply updating the package didn't work for us, we had to make sure the routes are named.

**Comment by tmeasday** [comment]
@brewhk-dev --- that is very surprising to me. Can you provide a simple reproduction of the problem?

**Comment by tmeasday** [comment]
Ok, released `iron:router@1.0.13`

**Comment by levino** [comment]
Wont fix with`iron:router@1.0.13` And I cannot use names easily as I have multiple "onBeforeActions". How would I give names to the routes then?

**Comment by tmeasday** [comment]
> Wont fix withiron:router@1.0.13

What does that mean?

I don't understand how naming routes could fix this problem if it still occurs with that version. It _removed_ code that looks at names.

**Comment by levino** [comment]
Edit: Removing this. Error on my side. Fix looks good.

**Comment by wbashir** [comment]
@tmeasday I tried adding this fix but with my Meteor version `1.1.0.2` I am running into an issue adding dependency packages.

```

$ meteor add iron:router@1.0.13
 => Errors while adding packages:             

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: iron:dynamic-template 1.0.12
Required by: iron:layout 1.0.12
Required by: iron:router 1.0.13
Required by: iron:router 1.0.13

```

Any ideas?

**Comment by tmeasday** [comment]
Looks like you may be on an old version of Meteor?

**Comment by CarlQLange** [comment]
Yep, updating middleware-stack worked for me. Nice job @tmeasday and all IR contributors :)

**Comment by martriay** [comment]
Just like @brewhk-dev, naming the routes worked for me while updating didn't

**Comment by wbashir** [comment]
@tmeasday I am indeed on an older version of Meteor and ended up updating the middleware-stack
