### ISSUE TITLE
refreshing/saving puts me in line 825 of source

### ISSUE THREAD

**Issue by kaiyes** [iron-meteor/iron-router#1516]
![screen shot 2016-02-25 at 7 54 40 am](https://cloud.githubusercontent.com/assets/5293742/13307392/13c20e82-db95-11e5-9827-ce3b6a7185fc.png)

As soon as I refresh, the app gets non-responsive and puts me in the  source line like that. changing back to previous commits where this problem didn't exist doesn't help either.

**Comment by mjmasn** [comment]
You've set a breakpoint in chrome, just click the line number to turn it off.

**Comment by kaiyes** [comment]
@mjmasn thanks a ton mate !!! Can't imagine missed something that basic...Cheers!!
