### ISSUE TITLE
Broken on Chrome Canary 

### ISSUE THREAD

**Issue by lorensr** [iron-meteor/iron-router#1520]
Today IR stopped working for me on latest OS X Canary – my 404 route always renders. Works fine on latest vanilla Chrome. 

On page load:

`iron_middleware-stack.js:198 Uncaught Error: Handler with name 'route' already exists.`

![image](https://cloud.githubusercontent.com/assets/251288/13584046/9f6a97ba-e482-11e5-99f4-9694b1b29d8a.png)

**Comment by lorensr** [comment]
Fixed by 7e6da3b

**Comment by joaopiopedreira** [comment]
Hi @lorensr, is this in production? I'm having this issue with my app after updating Chrome stable (it's not even Canary) today. Where is commit 7e6da3b? Can't see it anywhere... Cheers

**Comment by lorensr** [comment]
This is in the latest version. For more info see #1513
