### ISSUE TITLE
Meteor v1.3 - Organize your Meteor application

### ISSUE THREAD

**Issue by pgpbpadilla** [iron-meteor/iron-router#1522]
Steps
- Create example Todos app

``` bash
$ meteor create --example todos
$ meteor # Everything works just fine
```
- Upgrate to Meteor v1.3

``` bash
$ meteor update meteor update --release 1.3-modules-beta.8
```
- after restarting the app, we get:

``` bash
Exception in defer callback: Error: Oh no! No route found for path: "/"
    at Utils.extend.onRouteNotFound (http://localhost:3000/packages/iron_router.js?hash=d3f01d9d71ef43df008601f8ec06fd54bf37e6c6:1717:13)
    at IronRouter.dispatch (http://localhost:3000/packages/iron_router.js?hash=d3f01d9d71ef43df008601f8ec06fd54bf37e6c6:1204:19)
    at http://localhost:3000/packages/iron_router.js?hash=d3f01d9d71ef43df008601f8ec06fd54bf37e6c6:1669:12
    at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?hash=5acc047a258fc6c69c88e73b2b9ce69ae8f0fa9a:351:36)
    at new Tracker.Computation (http://localhost:3000/packages/tracker.js?hash=5acc047a258fc6c69c88e73b2b9ce69ae8f0fa9a:239:10)
    at Object.Tracker.autorun (http://localhost:3000/packages/tracker.js?hash=5acc047a258fc6c69c88e73b2b9ce69ae8f0fa9a:590:11)
    at Utils.extend.start (http://localhost:3000/packages/iron_router.js?hash=d3f01d9d71ef43df008601f8ec06fd54bf37e6c6:1666:10)
    at http://localhost:3000/packages/iron_router.js?hash=d3f01d9d71ef43df008601f8ec06fd54bf37e6c6:1461:16
    at _.extend.withValue (http://localhost:3000/packages/meteor.js?hash=940628dbd75c7e26a56bf59c2215c2108465064a:1031:17)
    at http://localhost:3000/packages/meteor.js?hash=940628dbd75c7e26a56bf59c2215c2108465064a:487:45
```

A [quick search](http://stackoverflow.com/a/26418732/400544) reveals that we need to update `iron:router` to `v1.0+` so we do

``` bash
$ meteor remove iron:router
$ meteor add iron:router 

Changes to your project's package version selections:

iron:controller        added, version 1.0.12
iron:core              added, version 1.0.11
iron:dynamic-template  added, version 1.0.12
iron:layout            added, version 1.0.12
iron:location          added, version 1.0.11
iron:middleware-stack  added, version 1.0.11
iron:router            added, version 1.0.12
iron:url               added, version 1.0.11
```
- We restart our app (not absolutely necessary since meteor is watching it)
- We get the promised screen: ![image](https://cloud.githubusercontent.com/assets/1960829/13892262/6e84cb72-ed13-11e5-9ac8-089da7f0a72f.png)

**Comment by pgpbpadilla** [comment]
Alright, it turns out it was because of the updates in the way the app is supposed to be structured.

I think the crucial step to make it work was to throw away all the config files for the old project and recreate it:

``` bash
$ rm -rf .meteor
$ meteor create .
```

After that I just needed to add the missing packages and move the files to their appropriate directories.

Now it's working: https://github.com/pgpbpadilla/todos-meteor-v1.3

**Comment by speciose** [comment]
Doesn't help in my case (not todo app). Still "Organize Your Meteor Application" msg.

**Comment by cyclops24** [comment]
@pgpbpadilla I have same issue as you tell here but your solution not working for me. Do you have any other suggestion??
My project works well on meteor 1.2.1 but now after update to 1.3.5.1 it's break at all and I see only `Organize your Meteor application` from iron-router.

I remove `.meteor` and recreate it. Which change needs on folder structure?
This is my current folder structure:

```
.
├── both
│   ├── collections
│   └── lib
├── client
│   ├── client.js
│   ├── lib
│   ├── styles
│   └── views
├── lib
│   ├── object_utils.js
│   └── string_utils.js
├── node_modules
│   └── jquery
├── package.json
├── public
│   ├── fonts
│   └── icons
└── server
    ├── collections
    ├── controllers
    ├── methods
    ├── publish
    └── server.js
```

Also my route inside `client/views/router.js`
I also ask it here: (please take a look if you have time)
https://forums.meteor.com/t/some-problem-for-update-one-project-from-1-2-1-to-1-3-4-4/26437
