### ISSUE TITLE
Chrome 51 seems to break iron router

### ISSUE THREAD

**Issue by stahlmanDesign** [iron-meteor/iron-router#1538]
Saw my site was not working in Chrome 51, but worked in Firefox and Safari, on OS X 10.10.5, Meteor 1.2. Checked on another computer that still had Chrome 50 and it was fine. Updated to Chrome 51. Now all paths resolve "Oops, looks like there's no route on the client or the server for url: ..."

middleware_stack.js
Line 31:
`throw new Error("Handler with name '" + name + "' already exists.");
`

**middleware_stack.js:31Uncaught Error: Handler with name 'route' already exists.**

**Comment by stahlmanDesign** [comment]
Forgive my haste. I updated to Meteor 1.3.2.4, and iron:middleware-stack  upgraded from 1.0.11 to 1.1.0

Now it works.

**Comment by phocks** [comment]
Can confirm. I was getting "Oops, looks like there's no route on the client or the server for url:" with a dot "." after the URL in Google Chrome, but it was working in all other browsers and on Mobile.

The fix is run `meteor update` and then `meteor update iron:middleware-stack`

**Comment by brewhk-dev** [comment]
This is a duplicate of #1297.

In summary:

Run `meteor update iron:middleware-stack`, if that doesn't work, ensure all routes in your route definitions are [named](http://iron-meteor.github.io/iron-router/#named-routes).
