### ISSUE TITLE
Problem with react

### ISSUE THREAD

**Issue by siwymilek** [iron-meteor/iron-router#1540]
Is any way to run iron-router only on server side? cuz it's not fit with React router

**Comment by eddiekollar** [comment]
Yes. There's an example in the **Quick Start** section:

``` javascript
Router.route('/files/:filename', function () {
  this.response.end('hi from the server\n');
}, {where: 'server'});
```

**Comment by thomasKn** [comment]
I think the question was: Is it possible to disable iron:router on client side?

I would also like to use react router for client side routing, but there is a conflict with iron:router.

I use iron:router combined with busboy to upload files on server side, and this is working fine. But I do not need iron:router on client side. I tried to disable the Autostart, but it didn't work.

@siwymilek, did you find a solution?

**Comment by tomtom87** [comment]
+1 

Is there any way to make iron-router disabled for the client apart from one route? e.g /admin

**Comment by chrisbutler** [comment]
@tomtom87 conceptually it's not really possible to disable the router but still have it respond to one route

but i just tested ```Router.options.autoStart = false;``` and it seems to work
