### ISSUE TITLE
where: 'server' -> Route not found

### ISSUE THREAD

**Issue by lugaru90** [iron-meteor/iron-router#1545]
Hey all,

i've got a Strange Problem. Using a Simple route where: 'server' and the response is a 404 Error. Any Ideas?

Code:

``` js
Router.route('/shop/confirmPayment',
  function() {
    this.response.statusCode = 200;
    this.response.end("success");
  },
  {where: 'server'});
```

**Comment by Batistleman** [comment]
In what file is this code located? Please make sure it's available for the server.

**Comment by lugaru90** [comment]
Damn it, always had the router.js inside the lib Folder. This time i've used a Template and the router.js was inside the Client. Thanks a lot Batistleman!
