### ISSUE TITLE
Iron.Url.fromQueryString not working as expected

### ISSUE THREAD

**Issue by ghost** [iron-meteor/iron-router#1555]
Issue #803 which has been closed adds a feature to easily allow access to a query string as an object. However this is not working as expect. 

The query string:

http://localhost:3000/?colour=red&colour=blue&colour=green&size=small&size=medium

When passed as an argument:

Iron.Url.fromQueryString('?colour=red&colour=blue&colour=green&size=small&size=medium')

returns Object {colour: "green", size: "medium"}

As you can see if a parameter appears more than once it is overridden.

Expected output would be:
returns Object { colour: ['red', 'blue', 'green'], size: ['small', 'medium'] }

**Comment by chrisbutler** [comment]
hey @tkiddle, there isn't really a standard for this... it could be enhance to support using square brackets (like PHP) to collect multiple params into an array, but i don't see the current functionality as being 'broken'
