### ISSUE TITLE
multiple template name error although there isn't.

### ISSUE THREAD

**Issue by ayazhussein** [iron-meteor/iron-router#1561]
everything was working before I updated to meteor 1.4.2.3 and updated iron router.
I have only one 'Home' template but I keep getting this error.
tried removing it and adding it again.. same error with the splash screen of "no route definition found", I tried changing my template name and edit the controller, I still get this error even though I don't have Home template anymore.
```Uncaught Error: There are multiple templates named 'Home'. Each template needs a unique name.
    at Function.Template.__checkName (templating-runtime.js?hash=c18de19…:55)
    at iron_router.js?hash=cb1b108…:2069
    at iron_router.js?hash=cb1b108…:2085
    at iron_router.js?hash=cb1b108…:2540```

**Comment by zimme** [comment]
Running into this problem also.

**Comment by kax0** [comment]
Seems that bdb65840386a7558cc5e91047230ef94450ea96a(v1.1.0) introduced the problem, downgraded to: `1.0.12` and it worked.

**Comment by marcoschwartz** [comment]
Some error here when upgrading to 1.1.0, had to downgrade to 1.0.13

**Comment by JackAdams** [comment]
Great to see work being done on iron router again, but the above is correct. 1.1.0 broke backwards compatibility.

**Comment by chrisbutler** [comment]
@ayazhussein @zimme @kax0 @marcoschwartz @JackAdams i think i know what's happening

for some reason in IR 1.1.0, meteor is pulling in everything in the examples/ folder

BUT this doesn't happen when i clone the same version locally. anyone have any ideas?

**Comment by ayazhussein** [comment]
@chrisbutler I noticed that, but isn't there a method where it checks if template name exists? also, I noticed that someone on stackoverflow had the same problem but a totally different template name, something like 'product_something_etc' and still had the same error..

**Comment by chrisbutler** [comment]
@ayazhussein was that a recent post? do you have the link?

**Comment by ayazhussein** [comment]
@chrisbutler 
http://stackoverflow.com/questions/41626562/iron-router-updates

**Comment by chrisbutler** [comment]
@ayazhussein @zimme @kax0 @marcoschwartz @JackAdams can you guys try 1.1.1 from atmosphere?

**Comment by zimme** [comment]
Seems to be working with `1.1.1`
