### ISSUE TITLE
Iron-router: No route definitions found.

### ISSUE THREAD

**Issue by dredl** [iron-meteor/iron-router#1564]
Good Day!
Try to use iron-router (v 1.1.0) on a new Meteor(v 1.4.2.3) project by simply installing _meteor add iron:router_
Then i've made simple example
[https://github.com/iron-meteor/iron-router/tree/devel/examples/basic](https://github.com/iron-meteor/iron-router/tree/devel/examples/basic)

After this i've got an error on browser console:
![image](https://cloud.githubusercontent.com/assets/9267716/21988125/50c17b82-dc30-11e6-9974-c6851284701f.png)

And there is a message that the _No route definitions found._

I spent one working day solve this problem but no results. Hope somebody help me. Thanks

**Comment by nguyendnhat** [comment]
Same with me
I'm put file router.js in folder lib, but it not working

**Comment by antoniogarcez** [comment]
Me too.
Cannot found this object: Package['iron:router'].Router;

To work, I have to downgrade to version 1.0.13 (meteor add iron:router@=1.0.13)

**Comment by bryanlimy** [comment]
+1

**Comment by chrisbutler** [comment]
@Sheriyev @nguyendnhat @antoniogarcez @bryanlimy can you guys try again with 1.1.1 from atmosphere?

**Comment by dredl** [comment]
@chrisbutler, I've updated with 1.1.1. Now it's working fine. Thank you :)

**Comment by bryanlimy** [comment]
@chrisbutler just tried 1.1.1 seems to be fine

**Comment by antoniogarcez** [comment]
@chrisbutler It's ok.

**Comment by danielGalvao** [comment]
1.1.2 fails for me

**Comment by chrisbutler** [comment]
@danielGalvao what errors are you getting?

**Comment by danielGalvao** [comment]
@chrisbutler 
iron:router
No route definitions found.
My routes.js in folder client/
I change my code with the example using my template name and not working too.

METEOR@1.4.3.1
iron:router@1.1.2

**Comment by chrisbutler** [comment]
@danielGalvao it works fine for me when i create a new app, add iron router, and add a route in the client folder
