### ISSUE TITLE
Img and Price Problem to router 

### ISSUE THREAD

**Issue by wendylop** [iron-meteor/iron-router#1567]
I can connect my router with the product deteil buy it is not complete . This fine not the img and price. 

<template name="productDetail">
    <div class="container" style="padding-top: 60px">
        <div class="row">
            <div class="col-md-7">
                <img src="/img/{{image}}" alt=""/>
            </div>
            <div class="col-md-5">
                <h1>{{title}}</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque quod fugiat vitae culpa dignissimos, eius suscipit explicabo doloribus, facilis eaque rem accusantium provident iure, excepturi ipsam vero voluptate odit earum.</p>
                <div class="row">
                    <div class="col-md-12">
                        <h3>{{price}} €</h3>
                        <hr/>
                        <p>
                            <a href="#" class="btn btn-success">
                                <i class="glyphicon glyphicon-shopping-cart"></i>
                                Añadir al carrito
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

'use strict';

Router.configure({
    layoutTemplate: 'layout',
    notFoundTemplate: '404'
});

Router.route('/', function () {
    this.render('products');
});

Router.route('/about', function () {
    this.render('about');
});

Router.route('/products/:id', function () {
    var that = this;
    var product = _.find(Products, function (prod) {
        return (prod.id === that.params.id);
    });
    this.render('productDetail', {
        data: product
    });
});

**Comment by chrisbutler** [comment]
hi @wendylop, there isn't really enough information here to help you. this also seems like a question that may be more suited for the meteor forums
