### ISSUE TITLE
Getting "Router is not defined" error?

### ISSUE THREAD

**Issue by Broham** [iron-meteor/iron-router#1568]
I am attempting to create a server side route inside of a file `/server/routes.coffee` using the following code:

```
Router.route("/revision", {where: "server"})
.get ->
  console.log "revision route...."
  ...
```

But when I start my app I get the following error: 

`W20170127-09:19:46.164(-8)? (STDERR) ReferenceError: Router is not defined`

When I do `meteor list` I see: 

`iron:router             1.1.1  Routing specifically designed for Meteor` 

(along with many other packages)

Can anyone see why I would be getting this error?

**Comment by chrisbutler** [comment]
i think we need more info (or a reproduction) to really be able to offer any help on this
