### ISSUE TITLE
Getting data for current route in onAfterAction

### ISSUE THREAD

**Issue by KaitaniLabs** [iron-meteor/iron-router#1569]
I'm really struggling to understand how to get the data context from the current route in an onAfterAction.

    OnAfterActions = {
        setDoc: function () {
            let routeName = this.route.getName();
            switch(routeName){
                case "MapView":
                    if (this.ready()) {
                        // 
                        // Need the data here
                        //
                    }
                break;
                default:
                    //
                break;
            }
            this.next();
        }
    };

I've tried: `.data, .data(), .getData()` with `this, Router, Router.current(), Router.route, this.route`, nothing seems to return anything. 

Any help would be very much appreciated.

**Comment by chrisbutler** [comment]
how are you adding the hook to the route?

it should just be ```this.data()```
