### ISSUE TITLE
Params - Query - undefined instead of string

### ISSUE THREAD

**Issue by escaroda** [iron-meteor/iron-router#1571]
I'm trying to pass parameter through query but Iron Router don't see it and get `undefined`

Here is this string: `one two three (12,34) = 360 +2%+250`
After `encodeURIComponent()` it looks like this:
```
one%20two%20three%20(12%2C34)%20%3D%20360%20%2B2%25%2B250
```

You can test it easily. Open any meteor project with iron router and add to link:
```
?notes=one%20two%20three%20(12%2C34)%20%3D%20360%20%2B2%25%2B250
```
then inside console run `Router.current().getParams()` and you'll see `query.notes = undefined`

**Comment by escaroda** [comment]
Any idea guys?

**Comment by chrisbutler** [comment]
@escaroda it's choking on ```%25``` which is the encoded '%' character

i found this existing issue: https://github.com/iron-meteor/iron-router/issues/1254

testing out a fix now
