### ISSUE TITLE
IE 9, infinity reload the page

### ISSUE THREAD

**Issue by nazarposhta** [iron-meteor/iron-router#1574]
Hi guys! I stuck with one bug. And Have no idea WTF is it. I use Meteor + Blaze + IronRouter on my project.

blaze-html-templates@1.0.4
iron:router@1.1.1
METEOR@1.4.2.3
Everything works "FINE" on most of browsers. Of course I blocked the web site for IE 8 (I show the message then user should update the browser) and want to do the same for 9-th. But that POS reloads browser infinitely and there is no chance to show the message about updating. Who has the same problem with IE 9? Or maybe some ideas how to fix it?

**Comment by chrisbutler** [comment]
are you able to look at the console and see any errors? i have an app running 1.1.1 that doesn't have this issue, so i don't think it's specific to iron-router
