### ISSUE TITLE
Render only one region

### ISSUE THREAD

**Issue by searje** [iron-meteor/iron-router#1576]
Hi,

I am quite new to Meteor / Iron Router.

I have an app with a layout with {{> yield}} and {{> yield "subcontent"}}.
One address "/main/:_pageNumber" sends a data context and template to {{> yield}}.
I would like to send another data context to {{> yield subcontent}} without re-rendering {{> yield}} via the address "/main/:_pageNumber/edit/:_id".

I manage to send both data context but both regions re-render. I would like to render only one and leave the other one.

Is there a way to do it ?

Thanks for the help !

**Comment by chrisbutler** [comment]
hey @16292 without seeing the actual code, it's tough to say why the re-rendering is happening
