### ISSUE TITLE
:someparameter returning empty array

### ISSUE THREAD

**Issue by ketankulkarni** [iron-meteor/iron-router#1577]
js code -
Router.route('/list/:someParameter', {
    data: function(){
        console.log(this.params);
    }
});

then url http://localhost:3000/list/hello was entered

expected o/p - [someParameter:"hello",hash:null,query:Object]

actual o/p -       Array[ ]

**Comment by chrisbutler** [comment]
hi @ketankulkarni, i can't reproduce this with the latest version... i need more info or a repo to look at
