### ISSUE TITLE
iron router error in PRODUCTION but working localhost

### ISSUE THREAD

**Issue by irshad-platalytics** [iron-meteor/iron-router#1585]
I am facing issue on Production but working fine locally.

iron:router
Organize your Meteor application.

Router.route('/', function () {
  this.render('Home', {
    data: function () { return Items.findOne({_id: this.params._id}); }
  });
});
        
Check it out on Github:
https://github.com/eventedmind/iron-router 

And check out the new Guide:
https://iron-meteor.github.io/iron-router

Can anyone guide to fix it?

**Comment by chrisbutler** [comment]
try running your app locally with the ```--production``` flag and checking the console for errors
