### ISSUE TITLE
Broken in Meteor 1.5?

### ISSUE THREAD

**Issue by boxxa** [iron-meteor/iron-router#1586]
Plain app from Meteor 1.5. As soon as you add in iron:router.

`
..../meteor/packages/meteor-tool/.1.5.0.q8vsrg++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Cannot read property 'get' of undefined
    at withoutInvocation (packages/meteor.js:443:33)
    at bindAndCatch (packages/meteor.js:452:33)
    at Object._.extend.defer (packages/meteor.js:514:26)
    at packages/iron_router.js:653:12
    at Function.time (/Users/desktop/Desktop/Meteor/TestApp/.meteor/local/build/programs/server/profile.js:309:28)
    at /Users/desktop/Desktop/Meteor/TestApp/.meteor/local/build/programs/server/boot.js:347:13
    at /Users/desktop/Desktop/Meteor/TestApp/.meteor/local/build/programs/server/boot.js:388:5
    at Function.run (/Users/desktop/Desktop/Meteor/TestApp/.meteor/local/build/programs/server/profile.js:510:12)
    at /Users/desktop/Desktop/Meteor/TestApp/.meteor/local/build/programs/server/boot.js:386:11
Exited with code: 1
Your application is crashing. Waiting for file change.
`

**Comment by villavong** [comment]
Try running
`meteor update --release 1.5.1
`
It seems it's not iron-router's error
[https://forums.meteor.com/t/meteor-crash-after-meteor-update/37858](url)

**Comment by boxxa** [comment]
This fixes it. Thank you. I closed the issue once I broke it down a bunch and found a 1.5 worked with Iron router and one didn't so didn't want to fillup the trouble queue. Thank you for the tip.
