### ISSUE TITLE
Iron router Issue with spiderable

### ISSUE THREAD

**Issue by kenshinman** [iron-meteor/iron-router#1593]
hi, I am having an issue with this package + spiderable

When i visit the normal url it works fine but when I visit with the url query `?_excaped_fragment_=`, I get the Iron router Page as though no route were configured.

How may i solve this please. Thanks

**Comment by kenshinman** [comment]
I have tried all the prerendering options
`prerender.io`, `spiderable (official)`, `jazeee:spiderable-longer-timeout`, `ostrio:spiderable-middleware`, `ongoworks:spiderable` but i keep getting iron:router splash screen

**Comment by kenshinman** [comment]
This issue has been solved. Iron router uses es6 which is not supported by all the spiderable packages i tried except `ostrio:spiderable-middleware` and that's the service that solved the issue.

**Comment by chrisbutler** [comment]
@kenshinman thanks for following up!

**Comment by kenshinman** [comment]
@chrisbutler is there going to be a resolution soon? ow just to wait for all spiderable packages to upgrade to es6
