### ISSUE TITLE
meteor iron:router not working

### ISSUE THREAD

**Issue by DDavis1025** [iron-meteor/iron-router#1601]
So I just started to use iron:router with meteor add iron:router with earlier versions as well and in my router.js file:

Router.route('/', function () {
  this.render('mainpage');
});

Router.route('/videopage'); 

and in a main.js file in my client without the router.js file

Router.route('/', function () {
  this.render('mainpage');
});

Router.route('/video', function () {
  this.render('video');
});

giving me this error

![screen shot 2018-09-26 at 2 00 36 pm](https://user-images.githubusercontent.com/9653985/46109246-da80e100-c194-11e8-9a19-859df7412a72.png)

This has worked for me in the past but not right now

**Comment by amka** [comment]
You have to create an .html file with `template` tag inside and add attribute `name` equals `mainpage` or `video`.
Like this:
```html
<template name="mainpage">
    <!--  Your content here -->
</template>
```
