### ISSUE TITLE
Internet explorer support?

### ISSUE THREAD

**Issue by solshark** [iron-meteor/iron-router#189]
Hi,

Is msie (any version) suported? Any plans?

**Comment by nazarposhta** [comment]
Hi guys! I stuck with one bug. And Have no idea WTF is it. I use Meteor + Blaze + IronRouter on my project.

blaze-html-templates@1.0.4
iron:router@1.1.1
METEOR@1.4.2.3
Everything works "FINE" on most of browsers. Of course I blocked the web site for IE 8 (I show the message then user should update the browser) and want to do the same for 9-th. But that POS reloads browser infinitely and there is no chance to show the message about updating. Who has the same problem with IE 9? Or maybe some ideas how to fix it?
