### ISSUE TITLE
React on leaving a specific page

### ISSUE THREAD

**Issue by nerdmed** [iron-meteor/iron-router#220]
I am trying to get a special behaviour in my application after leaving a specific page.
So i thought about applying an check on my last route inside an RouteController like this:

``` js
ApplicationController = RouteController.extend({
  before: function(){
    if(lastRoute=="xyz"){
      doSomething();
    }
  })
```

i tryed several ideas but nothing seems to get me the information about the route the user is coming from.

I also thought about adding this behaviour to the click handler of the link but this seems not a good solution because it doesn't cover the other cases that can bring the user outside of a route.

any ideas are appreciated!

**Comment by sasikanth513** [comment]
Is there anyway to stop routing to separate page?

For me both

```
window.onunload 
window.onbeforeunload
```

are not working, any luck @nerdmed @Multiply

**Comment by nerdmed** [comment]
@sasikanth513 i would recomment you to just use flow router, it solves a lot of those problems
