### ISSUE TITLE
Using Routers for subdomain

### ISSUE THREAD

**Issue by picsoung** [iron-meteor/iron-router#223]
Hello,

Quick question: I was wondering if I could use iron-router for subdomains in my app, like app.domain.com or admin.domain.com and they redirect to different views.

Thank you for your thoughts on that :)

**Comment by mr0-0nerd** [comment]
+1

**Comment by mahmoudkm** [comment]
+1

**Comment by Aselox** [comment]
+1

**Comment by dr-dimitru** [comment]
+1

**Comment by victorbstan** [comment]
+1

**Comment by satyavh** [comment]
+1

**Comment by iclear** [comment]
+1

**Comment by joaocarloscabral** [comment]
+1

**Comment by suhaildawood** [comment]
+1

**Comment by andrewhartline** [comment]
+1

**Comment by manuelmateus16** [comment]
+1

**Comment by sunstorymvp** [comment]
+1

**Comment by maomorales** [comment]
+1

**Comment by maxnatik** [comment]
+1

**Comment by maxnowack** [comment]
+1

**Comment by friktor** [comment]
+1

**Comment by Alino** [comment]
+1

**Comment by jasonnathan** [comment]
+1

**Comment by MaximeWillinger** [comment]
+1

**Comment by kevinpeter** [comment]
+1

**Comment by kevinpeter** [comment]
I've got a temporary solution for subodmains:

Meteor.startup(function () {
  if(Meteor.isClient) {
    //This code is needed to detect if there is a subdomain. So the system wants to know the routes of the subdomain
    var hostnameArray = document.location.hostname.split( "." );
    if(hostnameArray.length >= 3)   {
        var subdomain = hostnameArray[0].toLowerCase().ucfirst();
        var defineFunctionString = "define" + subdomain + "Routes";

        if (typeof window[defineFunctionString] === "function") {
          Meteor['is'+ subdomain] = true;
          window[defineFunctionString](); //To call the function dynamically!
        }
      }
      else {
        defineRoutes();
      }
    }
});

The default Routes (for example for bla.com) are defined in the function "defineRoutes".
If I call admin.bla.com the system automatic call the function for defineAdminRoutes. In this function I define all Routes for the Admin-Area. 
Another solution I didn't found.
