### ISSUE TITLE
Anchor tags dont work

### ISSUE THREAD

**Issue by FredericoC** [iron-meteor/iron-router#248]
When clicking a link with a hash that points to an anchor tag, the browser doesn't scroll to the anchor. 
As far as I know it is because of pushstate, but it would be good to have some sort of special link data attribute that would use window.location instead of pushstate for anchor links. Another option would be to simply check if the clicked link has a hash use window.location, but that can have other implications. Any thoughts?

**Comment by Zakkeri** [comment]
Since you need to let bootstrap to load you can use jQuery redy() function to get hash value from URL and tell browser to center at this hash (which is already there after page initialization)

Here is the code:

<code>$( document ).ready(function() {

    var hash = window.location.hash;

    window.location.hash = hash;
});</code>

**Comment by pferrel** [comment]
Meteor is great, client side rendering is great, server side rendering is great. Why can't we just get along? IMHO and in my site we have templates that should be client and ones that should be server. The design goal of Meteor should be to allow both with the least amount of special purpose coding. 

Throwing out hash named anchors to be implemented by users is not a good train of thought, it's in HTML5 so why doesn't Meteor out of the box support it consistently (internal anchors usually work but ones that trigger new rendering, like new URLs don't)? I've read lots of hacks and buck passing. Spiderable solves one use case, but seamless blending of client and server rendering would solve a lot more. I'd be happy if it worked at the template level so we could leave partials rendered on the client where desired but maybe there is a more elegant solution. I'd hate to see this thread as the last word in the discussion.

**Comment by MichaelJCole** [comment]
So, this is a standard HTML5 feature that Iron-Router breaks.  There's probably a good reason for that, but it took way to much time to work around.  Here's a quick fix for a simple template (based on above):

```
Template.TermsOfService.onRendered(function() {
  var hash = window.location.hash;
  if ($(hash).length) {  // if hash exists on page
    $('html,body').animate({
      scrollTop: $(hash).offset().top
    }, 200);
  }
});
```

**Comment by theosp** [comment]
If someone still need this, https://github.com/theosp/iron-location get my fork into your packages directory.

By using this fork, <a> tags that has the "permit-anchor" class will work properly when linking to intra-page anchors.

(Relevant change is in this commit: https://github.com/theosp/iron-location/commit/a5e6cfefea6f009599f1f978afbb436a2511619d)
