### ISSUE TITLE
Get current URL

### ISSUE THREAD

**Issue by Alexandre-Georges** [iron-meteor/iron-router#289]
Hi,

I was wondering if it is possible to get the current (parametrized) URL.
Using : Router.current().route.name is a bit too complicated for what I would like to do.

Thanks

**Comment by Nullpo** [comment]
Hi! There is any way to get the actual URL in a template? Or I have to create a custom helper for that?

**Comment by ramsaylanier** [comment]
window.location.href should work.

**Comment by endows** [comment]
I have not value 
```
Router.current().path
```
I had get current url this command.
```
Router.current().url
```

**Comment by dongaj** [comment]
Use This :
within a helper with this template Object Name
Router.current().route.path(this)

**Comment by micktaiwan** [comment]
As it is not consistent between localhost and my server, this is my solution:

```javascript
getUrl = function() {
  let url = Router.current().url;
  if(url.slice(0, 4) !== 'http')
    url = Meteor.absoluteUrl() + url.slice(1, url.length);
  return url;
};
```
