### ISSUE TITLE
Accounts-ui (ResetPassword, EnrollmentEmail modal) not works

### ISSUE THREAD

**Issue by elbowz** [iron-meteor/iron-router#315]
Sorry if this is a duplicate of #3, but I haven't found a solution and iron-router don't wants work.

When i click on ResetPassword link (http://localhost:3000/#/reset-password/:token) meteor redirect on '/'.

This issue is not resolved? 
I have seen some workaround, but i have to rewrite from scratch my template for manage ResetPassword, EnrollmentEmail, etc.

``` javascript
Accounts.urls.resetPassword = function (token) {
      return Meteor.absoluteUrl('reset-password/' + token);
};

this.route('resetPassword', {
        path: '/reset-password/:token',
        action: function() {
            Accounts.resetPassword(this.params.token, prompt('enter new password'), function () {
                Router.go('/');
            });
        }
    });
```

How can I use the template defined in account-ui (_forgotPasswordForm)?

thanks in advance

**Comment by katopz** [comment]
Hm, It's 2015 and I still stuck at this `http://localhost:3000/#/reset-password` , plenty of comment is deprecated and I'm doom.

Any update against current Meteor todos example version please give me a hint. Thanks

**Comment by DenisGorbachev** [comment]
@katopz Go with https://github.com/kadirahq/flow-router + https://github.com/meteor-useraccounts/flow-routing/

**Comment by stinghz** [comment]
I'm having this issue  too after upgrading to Meteor 1.3 , I'm getting url like , 
http://localhost:3000/#/reset-password/xxxxx
 http://localhost:3000/#/verify-email/xxxxxx

Any idea of how to fix  it is grealy appreciated! Thanks
I'm using flow-router

**Comment by csms0726** [comment]
me too +1
