### ISSUE TITLE
Help with setting up a route that sets the language

### ISSUE THREAD

**Issue by tanis2000** [iron-meteor/iron-router#316]
I would like to set the language of the app by calling URLs like this:

```
http://localhost/en/posts -> switch to English
http://localhost/it/posts -> switch to Italian
```

But I'd also like to be able to call an URL like this:
    http://localhost/posts .> and be redirected to http://localhost/en/posts

The reason behind this is to be able to send emails that contain the language in the URL, much like with RoR. Is this achievable with iron-router?

**Comment by obiwarn** [comment]
@timtch: Is that possible on a global scope, e.g. every route gets a /:lang/  prefix?
