### ISSUE TITLE
QUESTION: How to achieve nested routes, with there own data

### ISSUE THREAD

**Issue by zalavariandris** [iron-meteor/iron-router#337]
Is there an easy way to achieve nested routes, with there corresponding data.

Id like to have a bucket route, with a particular bucket as data. the bucket template would get the bucketData, and list its items as link. The item would appear next to the bucket, with the selected items as data to the temp ate, showing the item.

**Comment by thomasvanlankveld** [comment]
Hurrah for Ember-style route nesting!

While the iron router comes with a gazillion features, I prefer to use routing as an organisational tool. Lacking nesting support, this is precisely what the iron router does not facilitate.

In theory, a feature set as rich as the iron router's combined with nesting should be a 1 + 1 = 3 type of valuable.

**Comment by hafeez1042** [comment]
+1

**Comment by nscarcella** [comment]
+1
