### ISSUE TITLE
Hashes still don't work for basic behaviour

### ISSUE THREAD

**Issue by booshtukka** [iron-meteor/iron-router#373]
Firstly, in-page links to named anchors or IDs still don't work. Having a link with href of e.g. "#intro" won't jump to the div with the ID of "intro.

Secondly, if I want to react to the hash and use this behaviour myself, since i am using loadingTemplate, the element does not visibly exist.

It would be good to have some kind of option to either tell Iron Router to ignore hashes or pass a list of patterns or values to treat as regular in page links.

It would also be good to have an event that triggers when switching from the loadingTemplate to the standard template.

Am I misunderstanding something, and this functionality already exists?

**Comment by MichaelJCole** [comment]
Necro-ing this with an example: 

```
  onAfterAction: function() {
    Meteor.defer(() => {   // Wait till the page has loaded in next "tick"
      if (location.hash) {
        var navbar = 60;
        window.scrollTo(0, $(location.hash).offset().top - navbar);  // adjust for navbar
      } else {
        window.scrollTo(0, 0);  // scroll to top if no hash
      }
    });
  }
```
