### ISSUE TITLE
Iron-router not installing on Windows 7 with Meteorite

### ISSUE THREAD

**Issue by abhijitmallik** [iron-meteor/iron-router#387]
While trying to install meteorite through npm command "npm install meteorite" i got the error like

> sh ./completions/postinstall.sh

'sh' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! weird error 1
npm ERR! not ok code 0

Then When i run the mrt command in Window 7 it runs some window 7 inbuilt exe file.So please
help me how to install meteorite package and use iron-router in window 7.

**Comment by kalinr** [comment]
I was able to get this to work but I had to use `meteor add iron:router` instead of `meteor add iron-router`

**Comment by inasacu** [comment]
While using nitrous.io to develop an app I was able to user the above suggestion to install iron-router. use meteor add iron:router on nitrous.io
