### ISSUE TITLE
Controller level layout, that overrides configure.

### ISSUE THREAD

**Issue by Sivli-Embir** [iron-meteor/iron-router#41]
Being able to have a number of different layouts would be very useful. The configure layout option does not even take a function, as far as I could tell, so I could not even fake controller overrides.

Also I have a layout that depends on a the users collection so when they log out everything goes nuts. I don't even need a layout on the login page. I would like to say something to the effect of `layout: false`.

**Comment by tdmoneybanks** [comment]
Hi are we able to set multiple layouts now? @ryw does your updated solution still work?
