### ISSUE TITLE
POST call to server side route doesn't provide data object...

### ISSUE THREAD

**Issue by awatson1978** [iron-meteor/iron-router#452]
Hi there,

Trying to set up a simple REST API, using Iron-Router.  On the server, I've set up the following routing map:

``` js
Router.map(function () {
  this.route("apiRoute", {path: "/api/",
    where: "server",
    action: function(){
      console.log('------------------------------');
      console.log('apiRoute');
      console.log(this);
      console.log(this.body);
      console.log(this.data);
      console.log(this.query);

      this.response.writeHead(200, {
        'Content-Type': 'text/html',
        'Access-Control-Allow-Origin': '*'
      });

      if (this.request.method == 'POST') {
        console.log('POST');
      }
      this.response.end("success");
    }
  });
});
```

And in another application, I query that route by doing an HTTP call, like so:

``` js
HTTP.call("POST", 'http://localhost:3000/api/', "test string", function(error, result){
        if(result){
          //do something
        }
        if(error){
          //do something ELSE
        }
        done();
      });
```

In theory, the data object `test string` should show up in the server log.  Unfortunately, this is all I'm getting:  

``` js
I20140223-02:55:27.961(-5)?      url: '/api/',
I20140223-02:55:27.961(-5)?      method: 'POST',
I20140223-02:55:27.961(-5)?      statusCode: null,
I20140223-02:55:27.964(-5)?      _consuming: false,
I20140223-02:55:27.964(-5)?      _dumped: false,
I20140223-02:55:27.964(-5)?      httpVersionMajor: 1,
I20140223-02:55:27.964(-5)?      httpVersionMinor: 1,
I20140223-02:55:27.964(-5)?      upgrade: false,
I20140223-02:55:27.964(-5)?      originalUrl: '/api/',
I20140223-02:55:27.966(-5)?      query: {},
I20140223-02:55:27.966(-5)?      body: {},
I20140223-02:55:27.966(-5)?      files: {} },
```

As you can see, `this.query` and `this.body` are empty.  

I've tried shaping the data payload in various ways, such as replacing "test string" with a JSON object (which is what our Express REST API expects).  Tried things like this:

``` js
// var dataPayload = {text: "words!  and more words!"};
var dataPayload = {data: {text: "words!  and more words!"}};
HTTP.call("POST", 'http://localhost:3000/api/', dataPayload, function(error, result){
    // stuff
});
```

But that didn't seem to do anything either.  Any ideas on what I might be doing wrong?  
Thanks!

**Comment by matfin** [comment]
This is an issue I have also been having problems with, and cannot find a solution for. I have set up an endpoint inside a server side router so I can get notifications of Contentful.com updates and update my Server side collections accordingly.

With the content type set as 'application/vnd.contentful.management.v1+json' I run a post request from the command line like below, and this.response.body is blank

curl -H 'Content-Type: application/vnd.contentful.management.v1+json' -d 'test1=matt&test2=finucane' http://localhost:3000/hooks/contentful

Running the same command, without specifying the content type, it defaults to 'application/x-www-form-urlencoded' and the content comes through in the request body.

Has anyone encountered a similar issue and if so, how did you overcome it?

**Comment by mzamoun** [comment]
I post a request : mydomain/test
then : this.request.url will print : /test

How to print print the whole url (mydomain/test) ?

Thanks

See you soon 
Mourad
