### ISSUE TITLE
replaceState not working

### ISSUE THREAD

**Issue by rbabayoff** [iron-meteor/iron-router#461]
Hi,

Passing replaceState to Router.go doesn't work. Doesn't work in Router.redirect too.

Router.go call:

```
Router.go(path,{},{replaceState:true});
```

Github repo that reproduces bug:

https://github.com/juan-lavaina/iron-router-replace-state

Deployed app that reproduces bug:

http://replacestate.meteor.com/

Reproduced on Windows 7/8 - latest Google Chrome, FF, and IE 10.

Thanks,
Ronen
The LaVaina.com Team

**Comment by funkyeah** [comment]
Just commenting here since the comment by @tmeasday is no longer true and it gave me a small bump in the road.

calling `Router.go(path,{},{replaceState:true});` is now valid again
 
and calling `Router.go(path,{replaceState:true});` won't work anymore

**Comment by vicentealencar** [comment]
thanks for taking your time to write this comment @funkyeah, that saved me quite some time.

**Comment by fabyeah** [comment]
thanks from me as well, @funkyeah, this should really be documented.
