### ISSUE TITLE
Using Iron Router for url forwarding

### ISSUE THREAD

**Issue by crsssl** [iron-meteor/iron-router#466]
I'd like to be able to use my app for url forwarding on occasion. The app uses Iron Router. Is there some special coding that can accomplish this?

I've tried creating a route such as

```
  this.route('forwardto', {
    path: 'forwardto/:url(*)',
    layoutTemplate: "blankLayout",
    before: function() {
      this.stop();
      var url = this.params.url;
      if (typeof url === 'string' && !my_functions.urlIsValid(url)) { url = "http://" + url.trim(); }
      if (url) {
        this.redirect(url);
      }
    }
  });
```

...and it works, but...

It **always** renders my default `notFoundTemplate` before redirecting, which is annoying. (It even renders the default layout, despite my having overridden it.)

I've tried a path of `path: 'forwardto/*` as well as overriding all other parameters, AND I've even created its own Controller. No dice... it always flashes the default `notFoundTemplate`.

Here is the latest failure:

```
ForwardtoController = RouteController.extend({
  action: function () {
    this.stop();
    var url = this.params[0];
    if (typeof url === 'string' && !my_functions.urlIsValid(url)) { url = "http://" + url.trim(); }
    if (url) {
      this.redirect(url);
    }
  }
});

Router.map(function() {
  this.route('forwardto', {
    path: 'forwardto/*',
    template: "forwardto",
    controller: ForwardtoController,
    layoutTemplate: "blankLayout",
    notFoundTemplate: "forwardto",
    before: function() {
      this.stop();
      var url = this.params[0];
      if (typeof url === 'string' && !my_functions.urlIsValid(url)) { url = "http://" + url.trim(); }
      if (url) {
        this.redirect(url);
      }
    }
  });
});
```

What am I doing wrong? Or what else needs be done?
Thanks in advance.

**Comment by jazeee** [comment]
I know this is a closed issue, however, for completeness, I created a 301 redirect on the server side that worked correctly with Iron Router.  This link explains it quite well:
http://www.meteorpedia.com/read/HTTP_Redirects

**Comment by crsssl** [comment]
Thanks. I'll investigate this.
