### ISSUE TITLE
Using Different CSS for different layout template

### ISSUE THREAD

**Issue by ajduke** [iron-meteor/iron-router#488]
Hi, 
I am trying to integrate the Telescope application in our Meteor application.
For routing, our application will have route starting from '/' (uses layout template)
and Telescope application will have route starting from '/forum'. (uses another layout)
I am able to do it above, But problem is Telescope is being loaded into Meteor application and it is overriding CSS rules from our application.

In Iron-Router, is there any way to load the CSS files for particular layout template or can I make it a feature request ?

**Comment by nvhoc** [comment]
Hi,

I think the problem is good to avoid conflict css when we use another layout. Does it have any PR?
