### ISSUE TITLE
Uncaught ReferenceError: Router is not defined 

### ISSUE THREAD

**Issue by tobkle** [iron-meteor/iron-router#507]
branch: blaze-integration:
First I got the same problem like #506. I wasn't able to solve that problem, so I tried with a fresh 'mrt create new_project' and copied sources from old_project into new_project.

In new_project I'm getting with the same source code of old_project: 
Uncaught ReferenceError: Router is not defined 

within /client/lib/router.js    on:

Router.configure({
    layoutTemplate      : 'layout',
    loadingTemplate     : 'loading',
    waitOn: function(){ return Meteor.subscribe('nodes');}
});

Now applied #506 's fix to work with former old_project. This works. 

But I still don't know, what to do, to get the new_project running. I assume that this shouldn't be like that.

**Comment by CyberStrike** [comment]
I am running through Discover Meteor and just came across this. None of the fixes above have worked.

You can see my project here.

https://github.com/CyberStrike/meteor-microscope
