### ISSUE TITLE
Question: Way to wait for data to arrive and not just subscription ready

### ISSUE THREAD

**Issue by ko-lem** [iron-meteor/iron-router#513]
waitOn waits for a subscription to be ready. But being ready means that the data has already been sent by the server not that it has already arrived in the client (http://docs.meteor.com/#publish_ready).

This means I'd have to deal with the case where the data has not yet arrived when rendering.

So, let's say I have a challenges field in my users collection.

```
BasicController = RouteController.extend({
  waitOn: function() {
    return [
      Meteor.subscribe('currGame'),
      Meteor.subscribe('onlineUsersData')
    ];
  }
});
```

```
Template.game_board.helpers({
  online_players: function() {
    if (Meteor.user().challenges) {
      return // perform query that depends on challenges field
    } else {
      return [];
    }
  },

  challengers: function() {
    if (Meteor.user().challenges) {
      return // perform query that depends on challenges field
    } else {
      return [];
    }
  }
});
```

I have to place the if statement on all my helpers because sometimes at that point Meteor.user() only has the id, email, and username.

Is there a way to wait on the arrival of the data?

**Comment by victor-3wp** [comment]
Just Incase you’re using Iro-router,  you’ll need to write a pure JavaScript version of @scottburch ‘s solution, as meteor doesn’t compile es6 in iron-router
