### ISSUE TITLE
Iron Router not actually waiting on "waitOn" result

### ISSUE THREAD

**Issue by swese44** [iron-meteor/iron-router#554]
Subscriptions initiated in the waitOn function happen, but the router no longer waits on the result before rendering the template. Lots of great development here! Unfortunately this is a major blocker for my app.

**Comment by Dashman99** [comment]
HI @cmather I have a slightly different problem, my 'loading' template runs fine but I have a route (using Iron Router) which loads a template, and has a waitOn function and the 'loading' template never goes away, even though the data is loaded.  I'm using the sacha:spin spinner for the loading template.

I've had to obfuscate some of the data, so hopefully I have left the integrity in tact.

``` javascript
Router.route('/group/:Group', {
  loadingTemplate: 'loading',
  action: function() {
    this.render('itemList');
  }, 
  waitOn: function() {
    return Meteor.subscribe('groupItems', this.params.Group);
  },
  data: function() {
    return Wafers.find({Group: this.params.Group});
  }
});
```

And here's the subscription.js

``` javascript
Meteor.publish('groupItems', function(groupID) {
    return Wafers.find({Group: groupID});
})
```

I've also tried the loading template in the Router.config section with the same result.  I've tried several things actually, and above is just the latest.

``` javascript
Router.configure({

    layoutTemplate: 'layout',
    loadingTemplate: 'loading'
});
```
