### ISSUE TITLE
Action can be recalled before the data function, leading to template helper errors

### ISSUE THREAD

**Issue by tmeasday** [iron-meteor/iron-router#576]
I think there have been hard to reproduce bugs that have run across this problem, but I am seeing it on a project and I think I understand.

The basic issue is that sometimes you'll get a template rendered with data context `undefined/window`, even though you use `loading`, and `waitOn`. 

The reason is that you have written a `data` function _that doesn't check `this.ready()`_ (which is legit if it just does something like `Collection.findOne(this.params._id);`).

Because data and action run in separate computations, and in this case data doesn't depend on `this.ready()`, action _invalidates first when we become ready_ -- rerunning, bypassing the loading hook, and rendering the template with the old data value, which is `undefined`.

I'll make a reproduction to make it totally clear.

I think the solution is that we should _always_ wait before running data. Like I said in #569.

**Comment by proehlen** [comment]
I'm still seeing this but only regularly in Internet Explorer for some reason.  On OS X (Chrome, Safari and Firefox) plus mobile I cant see this happening.
