### ISSUE TITLE
onBeforeAction() running multiple times when waiting on multiple subscriptions

### ISSUE THREAD

**Issue by abecks** [iron-meteor/iron-router#592]
I'm having a problem where onBeforeAction() is executed multiples times before a Route is visited when waiting on multiple subscriptions:

``` javascript
    // Edit Client
    this.route('clientsEdit', {
        path: '/clients/edit/:_id',
        onBeforeAction: function(){
            console.log('before action');
            this.subscribe('CollectionOne').wait();
            this.subscribe('CollectionTwo').wait();
            this.subscribe('CollectionThree').wait();
            this.subscribe('CollectionFour').wait();
        },
        loadingTemplate: 'loading'
    });
```

Console Output:

```
hit before action
hit before action
hit before action
hit before action
```

onBeforeAction() seems to run once for every subscription. Is this intentional, or am I doing something wrong? onAfterAction seems to only fire once.

**Comment by tsega** [comment]
@cmather, I'm having a similar problem. I'm trying to count views of a post, in the `onBeforeAction` method of my route, as follows:

```JavaScript
Router.map(function () {
    this.route("post", {
        path: "/posts/:slug",
        data: function(){
            return {
                post: Posts.findOne({slug: this.params.slug})
            }
        },
        waitOn: function(){
            return Meteor.subscribe("posts");
        },
        onBeforeAction: function(){
            var postSlug = this.params.slug;
            var currentPost = Posts.findOne({slug: postSlug});

            console.log("Before Action Run");

            if(currentPost){
                if(Meteor.user()){
                    Posts.update({_id: currentPost._id}, {$push: {viewers: Meteor.userId()}});
                } else {
                    Posts.update({_id: currentPost._id}, {$inc: {anonymousCount: 1}});
                }
            }

            this.next();
        },
        onStop: function(){
            var postSlug = this.params.slug;
            var currentPost = Posts.findOne({slug: postSlug});

            console.log("Stop Action Run");

            if(currentPost){
                if(Meteor.user()){
                    Posts.update({_id: currentPost._id}, {$pop: {viewers: Meteor.userId()}});
                } else {
                    Posts.update({_id: currentPost._id}, {$inc: {anonymousCount: -1}});
                }
            }

            this.next();
        },
        template: "post"
    });
});
```

The moment I include the code to check for the current post and update it, the execution goes into an endless loop (see my console log screenshot below). I just can't seem to figure out what it is.

One other thing, is my use of the `onStop` action correct? The whole idea is to decrements the number of views when the user leaves the `currentPost` page.

![image](https://cloud.githubusercontent.com/assets/206924/5838962/fd300acc-a19b-11e4-92e1-c6fd3ecc6b1c.png)

**Comment by copleykj** [comment]
@tsega You'll just want to change your onBeforeAction to an onRun. 

onBeforeAction is run inside a reactive computation. When you make a call to findOne this creates a dependency. When you then call update on the collection it tells the computation that the dependency changed and the computation invalidates causing the function to be ran again with the same thing happening thus causing an Infinite Invalidation Loop.

**Comment by tsega** [comment]
@copleykj I knew there was something funny going on like that but I just couldn't put my finger on it. It totally makes sense! Thanks for the help!
