### ISSUE TITLE
Bug: UI.body events do not fire.

### ISSUE THREAD

**Issue by cmather** [iron-meteor/iron-router#606]
This could be an issue with blaze-layout, or the way Iron Router is calling the render method of the layout. I thought providing a parent component as an argument to UI.render would solve this in blaze-layout, but I must have missed something.

**Comment by keyscores** [comment]
One year later on Meteor 1.1.0.4 I'm still having issue with UI.body and Iron Router. Is this closed because it's solved, or is there another ticket open?

**Comment by mkarliner** [comment]
I'm also getting this, however, only in Safari or Firefox, Chrome works as expected.

**Comment by samhatoum** [comment]
I'm also getting this. Installing @gwendall's package fixed it

**Comment by robertdavid010** [comment]
I have initial confirmation of this issue persisting.

Had an event triggered in Template.body.events() which worked fine (the trigger element is nested within another template).

Added Iron:Router to the project and this no longer worked.

Added the event trigger to the template specific events function, and it worked.

The issue must be in iron:router's creation of the`<body>` element (separately from the Blaze rendering of it?) and Meteor not being able to recognize this IR generated `<body>` element. That's my initial thoughts anyway.

It seemed to be handy to be able to track events globally from the Template.body.events() function. If this is an intended feature of Meteor, it would be great if IR didn't break it.

## 

R
