### ISSUE TITLE
Authenticating in server-side route?

### ISSUE THREAD

**Issue by timspro** [iron-meteor/iron-router#649]
Is it possible to authenticate in a server-side route? I tried simply calling Meteor.user() in a server-side route but I got the error: "Meteor.userId can only be invoked in method calls. Use this.userId in publish functions." I also tried to simply wrap a server method around Meteor.user() and call that method from the server-side route. This didn't produce an error but it also didn't correctly tell me i was logged in. 

Given that many apps need user authentication to access the appropriate data from a collection, it seems like this is a good/necessary feature, but if it is possible, I haven't found any information about it.

I see that reststop2 can do authentication, but I don't think it would play well with Iron Router in the same project. 

If it isn't possible, then what would be the canonical way to provide a REST API to verify that a user is logged in?

**Comment by faceyspacey** [comment]
yea, i dont know what everyone is talkin about, but @alethes's solution works reliably. Perhaps its because we're both using fast-render--but you should be using that anyway. Problem solved. Iron router should have a this.userId() on the object that has this.request and this.response, i.e. the context of ur route functions

**Comment by sdistefano** [comment]
@faceyspacey I'm not sure what problem this is that relates to Meteor's internals, but @alethes solution is working very unreliably for me. After a couple of attempts I remain logged in on the client but the server no longer recognises it

**Comment by dasdeck** [comment]
What about this issue? May it be the cookie is no longer parsed in latest versions? It may also be my custom login routine, I still use Meteor's auth model thought. 

edit:
Seems to me that my custom authorisation does not stick when I add fast-render :/ .

**Comment by mhagmajer** [comment]
I recently wrote a blog post describing solution to this: https://blog.hagmajer.com/server-side-routing-with-authentication-in-meteor-6625ed832a94.

If you need authentication, you basically need to set up a server route using a https://atmospherejs.com/mhagmajer/server-router package and you can get current user with `this.userId` just like with Meteor methods.
