### ISSUE TITLE
 Uncaught Error: _id not found in params (problem with parsing url parameters)

### ISSUE THREAD

**Issue by awatson1978** [iron-meteor/iron-router#65]
Hi again,
Following the instructions on the Iron Router, and it doesn't seem to be parsing parameters after a ? character.  :(

As I mentioned in the other thread, I'm working on this OAuth project.  Without going into all the details, suffice it to say that the external server (stripe.com) is doing a redirect to a page on my server, and is handing off a parameterrized URL which I'm trying to parse.  Here's the basic scenario: 

``` javascript
// I specified the following URL redirect route as part of setting up OAuth
localhost:3600/stripe

// and the oauth authentication process successfully redirects to the following URL
localhost:3600/stripe?scope=read_only&code=ac_2QGZP0nOBmb0Lxk9q3pMzaRvOi4fMU8j

// with the following parameterized tokens I need to use for future API calls
?scope=read_only&code=ac_2QGZP0nOBmb0Lxk9q3pMzaRvOi4fMU8j

```

So far, so good.  Mostly, I'm just interested in getting that code `ac_2QGZP0nOBmb0Lxk9q3pMzaRvOi4fMU8j`, which changes at every login, and which I need as a security token to use the rest of the API.    So, here's what I'm trying to do, and the error messages it's giving me:

``` js
Router.map(function() {
    this.route('home', {path: '/'});
    this.route('stripeConnect', {path: '/connect'});
    this.route('aboutUs');
    this.route('charge');

    // so, i tried to set up a route, as per the basic instructions, and it generates the following error:
    // Uncaught Error: _id not found in params 
    this.route('stripeRedirect', {
      path: '/stripe/:_id',
      data: function() { //return Posts.findOne(this.params._id); 
        return true;
      }
    });

    // bah.  so, I tried dozens of other changes; lots of stuff that looks like this. 
    // same basic error though - Uncaught Error: slug not found in params 
    this.route('stripeRedirect', {
          path:'/stripe/:slug'}
    ), function(){
        console.log(this.params.code);
        console.log(this.params.slug);
    };

   // then, I thought I'd be really clever, and do something like this, but no luck
   // Uncaught Error: _id not found in params 
   this.route('stripeRedirect', {
        path: '/stripe?scope=read_only&code=:_id'},
        function(){
        console.log(this.params._id);
        }
    );

    // another failed attempt
    this.route('stripeRedirect', {
            path: '/stripe'},
        function(){
            console.log(this.params.code);
        }
    );


});
```

As far as I can tell, it seems to have something to do with the router not parsing the `:slug` component in the path lines, like so `path:'/stripe/:slug'`.

Any thoughts on how to proceed?  Thanks in advance for any suggestions!
Abigail

**Comment by shubham-daffodilsw** [comment]
I am using router.go to route to a path . I am giving parameters inside the query object of router.go .
The problem is the parameters are adding along with the url , which is not desirable in my case .

  Router.go('smsVerification', {foo:'bar'}, {query: queryData,foo3:'bar3'},{fooNew:'barNew'});

    this.route('smsVerification', { name: 'smsVerification',path: '/smsVerification',data:function(){
        return {
            mobileNo: this.params.query.mobile_no
        };
    }});

what can i do for sending parameters in router.go and the parameters should not be shown in the url.
