### ISSUE TITLE
Global onBeforeAction  hooks not working

### ISSUE THREAD

**Issue by jhuenges** [iron-meteor/iron-router#683]
Hey, I have a problem using the global `onBeforeAction` hooks. 
The global hook `Router.onBeforeAction(filters.isLoggedIn, {only: ['home']});` doesn't work but the one defined in the route does.

``` javascript
this.route('home', {
        path: '/',
        yieldTemplates: {
            'home': {to: 'content'}
        },
        onBeforeAction: function (pause) {
            if (!Meteor.user()) {
                this.render('login', {to: 'content'})
                pause();
            }
        }  
    });
```

Thanks in advance!

**Comment by llvasconcellos** [comment]
@JohnAllen I have the same problem. Did you solve yours? I realize that the waiton() function interferes with the onBeforeAction.
