### ISSUE TITLE
Hooks with the ability to abort route navigation

### ISSUE THREAD

**Issue by optilude** [iron-meteor/iron-router#698]
Following on from http://stackoverflow.com/questions/24367914/aborting-navigation-with-meteor-iron-router, I have been trying to step through the `iron-router` sources to understand whether there are any hooks that are capable of aborting navigation.

As far as I can tell, it's not possible to abort an attempted route. The use case is stopping users from navigating away from a page with unsaved data, a bit like an `onunload` event in a traditional webapp.

I have tried using both `onStop()` (to abort the current route) and a global `onBeforeAction()` hooks (to pause the navigation), but it seems that the URL is changed via `IronLocation` regardless, in the `done()` callback inside `Router.go()`, which is called in `Router.run()` before `self._currentController._run()`.

It's possible to force navigation "back" (via `Router.go()` inside a hook), but here the data is lost as everything is re-rendered, and it gets very messy.

**Comment by mpranjic** [comment]
This would be so useful. Has anyone started working on it?

**Comment by nixoz** [comment]
Guys, any updates on this issue?

**Comment by JamesLefrere** [comment]
Does https://github.com/ephemer/meteor-before-leave-previous do what you ask?

**Comment by hellogerard** [comment]
@JamesLefrere I very quickly just tried that package in my app on the latest IR (1.0.7) and it didn't work :-(  (I did not try to create a small, example app to see if it worked.)

**Comment by Siyfion** [comment]
I have to say that it's a real shame to see that nearly a year on from when this issue was first raised, I too am now running into this same issue, with little progress seemingly being made. :frowning: 

Has there been an update somewhere that I've missed regarding this? Is it still something that is planned to be implemented at some point? Or has it been decided that it's not useful / wrong?

**Comment by lance-anderson** [comment]
+1

**Comment by Billybobbonnet** [comment]
+1

**Comment by Billybobbonnet** [comment]
Hello folks,

I found a workaround using the publication/subscription mechanism. Have a look here for more details: http://stackoverflow.com/a/31764302/3793161

Tell me what you think about it!

**Comment by patte** [comment]
+1

**Comment by involve-it** [comment]
+1 for such basic functionality implementation!
And found this package, which seems to not work: https://github.com/ephemer/meteor-before-leave-previous

**Comment by ClarenceL** [comment]
+1 This really needs to be added

**Comment by gsabran** [comment]
+1, that'd be very useful

**Comment by elpddev** [comment]
Any news on this ? Detecting and be able to abort route changes would be extremely useful.

**Comment by chrisbutler** [comment]
i'm a little confused about the use case for this functionality... i'm pretty sure that this can be achieved in a number of other ways

**Comment by calebl** [comment]
@chrisbutler can you elaborate? I still haven't found any way to accomplish this.

**Comment by chrisbutler** [comment]
what are you trying to do in your app?

**Comment by elpddev** [comment]
My use case is showing a warning dialog when trying to leave a SPA page to other route if changes are not saved. There are many places the user can leave the section and route to another section by the main navbar for instance. 

This would be helpful if it can be accomplished by capturing the change of route and be able to cancel it if a flag is not set by the app for instance. Something like in Angular ui router $stateChangeStart event, which is basically some kind of aspect oriented programming and suit the router as the place to put this logic.

**Comment by chrisbutler** [comment]
So you should be able to override Router.dispatch (see https://github.com/iron-meteor/iron-router/issues/553#issuecomment-119002237) but you'll also need to call the following in your overridden function to avoid the url changing:

```
var loc = Iron.Location.get();
loc.cancelUrlChange();
```

(reference: https://github.com/iron-meteor/iron-location/commit/e540a374b85d2e8cb7885d835a9d5e4efaa6cc94)

**Comment by elpddev** [comment]
@chrisbutler Thank you for the direction. It works, but almost. The logic of the caller of the dispatch is not build for client cancellation of route change. 

The previous location is always set to the newly tried location, even when that is canceled. It means that even after cancellation, the link that was tried to be entered will not react anymore until other is selected.

`prevLocation = loc;
`
https://github.com/iron-meteor/iron-router/blob/bdb65840386a7558cc5e91047230ef94450ea96a/lib/router_client.js#L200

```
/**
 * Start reacting to location changes.
 */
Router.prototype.start = function () {
  var self = this;
  var prevLocation;

  self._locationComputation = Deps.autorun(function onLocationChange (c) {
    var controller;
    var loc = Iron.Location.get();
    var hash, pathname, search;
    var current = self._currentController;

    if (!current || (prevLocation && prevLocation.path !== loc.path)) {
      controller = self.dispatch(loc.href, null, function onRouterStartDispatchCompleted (error) {
        // if we're going to the server cancel the url change
        if (!this.isHandled()) {
          loc.cancelUrlChange();
          window.location = loc.path;
        }
      });
    } else {
      self._scrollToHash(loc.hash);
      // either the query or hash has changed so configure the current
      // controller again.
      current.configureFromUrl(loc.href);
    }

    prevLocation = loc;
  });
};
```

Is there a way of canceling that saving of prevLocation other than changing the router code ?

After more checking, there is also a private prev location state saving in the Iron location go method that is preventing going to the previous url needlessly.

**Comment by chrisbutler** [comment]
@elpddev aha, i see... in that case the next-best solution is to bypass the router completely:

```
$( "a" ).click(function( event ) {
  event.preventDefault();
  if (confirm('are you sure?')) {
    $('a').unbind('click');
    $(event.currentTarget).click();
  }
});
```

i appreciate you digging in and figuring out that the prevLocation is being saved this way... i would be willing to release a fix/add this functionality if we can figure out exactly how it should work

maybe as described in https://github.com/iron-meteor/iron-router/issues/457#issuecomment-74822133 but you could also call ```this.stop()``` in addition to ```this.next()```?

**Comment by elpddev** [comment]
@chrisbutler Thank you for the time and reply. I will try to investigate and try more when I will reach this functionality again in my project.

Regarding the "a" click bypass, that's a partial solution. There are cases when activating the route is from within the code with Rotuer go for instance and this will not catch that.

**Comment by chrisbutler** [comment]
@elpddev you can combine it with overriding ```Router.go``` (the same way as ```Router.dispatch``` above) or just check your conditions before calling ```Router.go``` in the first place

**Comment by laddi** [comment]
I'm also interested in this, specifically to allow routes to be "blocked" based on current user privileges (meteor/alanning:roles).  To prevent a user from navigating to a particular URL you would need to check, before the route change, if it has privileges to see the route and possibly show a 403 (or a 404).  Using `onBeforeAction` will always navigate to the route first with a change in the browser which is not the ideal solution.

If anyone has found a good solution for this, I'm all ears! 😄

**Comment by MohammedEssehemy** [comment]
@laddi 

check [this comment](https://github.com/iron-meteor/iron-router/issues/698#issuecomment-312350115)
and [this comment](https://github.com/iron-meteor/iron-router/issues/553#issuecomment-119002237)
