### ISSUE TITLE
Back button doesn't render template

### ISSUE THREAD

**Issue by bitomule** [iron-meteor/iron-router#722]
I'm having some problems with iron-router.
1. Routes inside a links doesn't work client side, they work server side so browser ask server for the new route and page is loaded (slow)
2. Router.go works and updates template as expected, but going back using Chrome back button changes the route but doesn't reload the template so it displays the old content.

I use a loading template on all the routes and also waitOn in all the routes. I've tried using a custom action in both routes and calling this.render when it's ready and all is called fine.

Router.go -> Render project page
Back button -> Render home but nothing changes

Thanks!

**Comment by Maxhodges** [comment]
OK to close.
