### ISSUE TITLE
Router.go(.., {replaceState: true}) isn't supported.

### ISSUE THREAD

**Issue by mitar** [iron-meteor/iron-router#764]
I would like to do something similar to HTTP 302 redirect. In browsers when you make a HTTP 302 redirect, browser history does not show previous location, only destination location. Also clicking back skips the location you had redirect from.

How can I do this in iron-router? In `Rotuer.go()` modifies history.

**Comment by nicolamr** [comment]
Why is this closed? Seems to me it still isn't supported (couldn't find replaceState at all in the repository).

**Comment by baconmania** [comment]
@nicolamr it is indeed supported: https://github.com/iron-meteor/iron-location/blob/f3e1e787483360a7122a07e309322edf992a0312/lib/location.js#L96-L97

The signature is 
```javascript
Router.prototype.go = function (routeNameOrPath, params, options)
```

Pass `{ replaceState: true }` for `options` and you should be all set.

**Comment by luca-aurelia** [comment]
Are there still plans to change `redirect` to automatically include the `{ replaceState: true }` functionality? With the current implementation, if you call `redirect` inside a route it breaks the back button. See [this](http://stackoverflow.com/questions/26487332/iron-router-redirect-without-killing-back-button-functionality) StackOverflow question.
