### ISSUE TITLE
Access to Meteor.userId() on server side routing

### ISSUE THREAD

**Issue by adoyen** [iron-meteor/iron-router#851]
Hello,

In order to share files on the server with access restriction, I need to access Meteor.userId() or anything else giving me the current userId.

As far as I can see, the userId is not known on server side routing.
By now, I receive an error specifying I need to use this.userId() which is not defined aswell (it's the same error than the one I receive when using Meteor.userId() in publications).

Maybe do you have a better solution to share restricted files using client side routing ?

Thanks for any help,
Regards,
Arnaud.

**Comment by rajit** [comment]
Is this something being considered or worked on currently?  Access to the user in server-side routes would be great and of course make routes more complete.  Routes that utilise Meteor.userId without an explicit 'where' option currently will fail any time the route can't be executed client-side.

**Comment by mhagmajer** [comment]
You may check out https://github.com/mhagmajer/server-router for server routing with authentication. I also wrote a blog post describing the issue in great detail https://blog.hagmajer.com/server-side-routing-with-authentication-in-meteor-6625ed832a94
