### ISSUE TITLE
Can't use regular expression routes: `Cannot currently resolve a regular expression path`

### ISSUE THREAD

**Issue by LeCoupa** [iron-meteor/iron-router#887]
When I'm trying to define one of my route's path with a regex, the chrome debugger says:

```
Exception in template helper: Error: Cannot currently resolve a regular expression path
```

That's strange. In previous version of Iron Router, this was possible?

**Comment by fvpDev** [comment]
https://github.com/DerMambo/ms-seo/issues/84
