### ISSUE TITLE
same route reload

### ISSUE THREAD

**Issue by sasi513** [iron-meteor/iron-router#890]
Here is my iron-router route

```
    this.route("video",{
      path:'/video/:_id/:slug',
       waitOn: function() {
         Session.set("currentTitle",this.params.slug);
         Session.set("currentVideoId",this.params._id);
         console.log("waitOn");
       },
      onBeforeAction: function () {
      },
      action:function(){
        console.log("action");
        this.render();
      },
      data:function(){
        console.log("data");
            var video= Videos.findOne({_id: this.params._id});
             if(video){
              console.log("set the url");
              Session.set("currentVideoURL",video.videourl);  
              Session.set("thumb",video.thumbs);  
            }            
            return {
              video:video
            };
      }
});

```

On the template rendered event I'm calling some meteor method and processing the result

```
Template.video.rendered=function(){
        console.log("rendered event");
        var id=Session.get("currentVideoURL");
        Meteor.call("getdata",id,function(e,d){
            //processing
        });
};

```

and in my html, I'm displaying some relative videos, on click of those videos I want to open the same page with this video data

but the video variable data in router's data method is resetting and the rendered event is not firing(I didn't seen render event in console),

I want the page to open as we are coming from another url, I want all the events to be fired.

How to acheive this?

**Comment by hadynz** [comment]
> The decision was made at some point that you can't route to the same URL.

@tmeasday Are you able to point me to where abouts this behavior is taking place? I would like to somehow suppress it for a given number of client routes in my app. Using a reactive var in `data()` could potentially be the way to go around this problem, however, I am wary on the complexity this would introduce in places were this is required.

My use case is that when a user goes to a URL such as `/edit/1`, a modal edit form is shown to the user. The user then has the option to close the modal, and re-open it again; hence the need to be able to rerun the same route.

Creating a solution based on client routes only, and without a mixture of events is the idea solution that I am trying to achieve = simplicity.
