### ISSUE TITLE
Routes not working if placed inside “if (Meteor.isClient)”

### ISSUE THREAD

**Issue by ghost** [iron-meteor/iron-router#897]
Environment: iron:router@1.0.0-pre3 with meteor 9.3.1.

<--- html --->

```
<head>
  <title>ironman</title>
</head>

<body>
</body>

<template name="hello">
  <p>Hello.</p>
</template>
```

<--- js --->

```
if (Meteor.isClient) {
    Router.route('/', function() {
        this.render('hello');
    });
}
```

The route is not working in the above case. However, it works properly if route is placed outside "if (Meteor.isClient) {".

**Comment by awgneo** [comment]
Are non-global routes supported yet? It would be essential to allow this in a modular plugin system (similar to rails) where plugins (/packages) can apply additional routes to the overall system.

**Comment by LeonineLabs** [comment]
^ Also wondering how I can declare routes in a smart package.

**Comment by davidefendi** [comment]
good day..>>
