### ISSUE TITLE
Router not working!

### ISSUE THREAD

**Issue by rclai** [iron-meteor/iron-router#907]
I have this in `/lib/router.js`

```
Router.configure({
  layoutTemplate: 'layout',
});

Router.route('/', function () {
    this.layout('layoutHome');
    this.render('home');
});
```

And I have this in `/client/views/layout.html`

```
<template name="layout">
    {{> header }}
    <div class="container">
      {{> yield }}
    </div>
</template>

<template name="layoutHome">
    <div class="header-bg">
        {{> header }}
        {{> search }}
    </div>
    <div class="container">
        {{> yield }}
    </div>
</template>
```

And this in `/client/views/home.html`

```
<template name="home">
    hello world come on!
</template>
```

When I go to the home page `/`, it throws this error on the client console:

```
Exception from Tracker recompute function: Error: Couldn't find a template named "/" or "". Are you sure you defined it?
```

Why is it looking for a template called '/' when I clearly specified the template to render?

Is it possible for a package to cause it to not work properly? Here's my `meteor list`

```
accounts-password                  1.0.2  Password support for accounts
autopublish                        1.0.0  Publish the entire database to all ...
insecure                           1.0.0  Allow all database writes by default
iron:router                        0.9.4  Routing specifically designed for M...
less                               1.0.9  The dynamic stylesheet language
meteor-platform                    1.1.1  Include a standard set of Meteor pa...
mizzao:bootstrap-3                 3.2.0_1  HTML, CSS, and JS framework for d...
yasinuslu:accounts-ui-bootstrap-3  0.3.10  Bootstrap styled version of login ...
```

In order to make it work, I have to write the routing using the legacy code:

```
Router.configure({
  layoutTemplate: 'layout',
});

Router.map(function () {
    this.route('home', {
        path: '/',
        layoutTemplate: 'layoutHome'
    });
});
```

**Comment by MHerszak** [comment]
I have the same issue and I am on iron router version 1.0.7. I have 4 templates going into layoutTemplate. On some routes Meteor renders the correct layout but on some it just renders a layout witch is not defined for this route nor as default per Router.configure. I am using yogiben/meteor-starter.

Thank you.

**Comment by phtn** [comment]
Having the same issue with version 1.0.7 in mobile Chrome. It loads "/" page but white blank pages for the rest of my routes. I tried mobile Firefox and it works just fine. 

I think iron:router have incompatibility issues with other dependencies. i don't know..
