### ISSUE TITLE
this.request.files no longer works under 1.0.0 pre

### ISSUE THREAD

**Issue by Tarang** [iron-meteor/iron-router#909]
In 0.9.4 its possible to use `this.request.files` to retrieve any files uploaded to the server via a multipart POST request.

I'm not sure whether it was intended but the same bunch of code no longer provides any files for the exact same requests with `iron:router@1.0.0-pre3`.

If it was intentional is there a way around this?

**Comment by cfsamson** [comment]
Just posting this for completeness. If you want to pass your files together with the request or store them in mongodb, you can use this (beware that this stores them in memory though):

if (Meteor.isServer) {
    var Busboy = Npm.require("busboy");

    Router.onBeforeAction(function (req, res, next) {
        var files = []; // Store files in an array and then pass them to request.

        var image = {}; // crate an image object

        if (req.method === "POST") {
            var busboy = new Busboy({ headers: req.headers });
            busboy.on("file", function (fieldname, file, filename, encoding, mimetype) {
                image.mimeType = mimetype;
                image.encoding = encoding;

                // buffer the read chunks
                var buffers = [];

                file.on('data', function(data) {
                    buffers.push(data);
                });
                file.on('end', function() {
                    // concat the chunks
                    image.data = Buffer.concat(buffers);
                    // push the image object to the file array
                    files.push(image);
                });
            });

            busboy.on("field", function(fieldname, value) {
                req.body[fieldname] = value;
            });

            busboy.on("finish", function () {
                // Pass the file array together with the request
                req.files = files;
                next();
            });
            // Pass request to busboy
            req.pipe(busboy);
        }
        else{
            this.next();
        }


    });
    }

You can then store them in your db or somewhere else like this:

Router.route('/files/image/upload', function () {
    // we assume only one image here
    var image = this.request.files[0];
    var id = mydb.images.insert(image);
    var res = {
        link: '/image/' + id
    };

    this.response.end(JSON.stringify(res));

}, { where: 'server', name:'imageUpload' });


This exact example returns a link for the Froala WYSIWYG editor, but it's just an example.

**Comment by flyandi** [comment]
So is this right Iron:Router doesn't support reading directly Post data?

**Comment by mickeyren** [comment]
hey guys - any update on this? Can we no access the file data from a form with Iron Router 1.0.8?

**Comment by jfurneaux** [comment]
Be careful with the capitalization of 'Busboy' - if you don't use the correct lower case Meteor.npmRequire("busboy"), it will work in dev, but fail on certain prod environments. There's a thread resolving this and I suspect this may be the source of the mistakes.

**Comment by daslicht** [comment]
So using busboy is a must ?

**Comment by nicejwjin** [comment]
Yeah. It seems like working quiet well using Busboy,
I think this is kind of basic functionality-
Hopefully- to be getting easier!

**Comment by mushkab** [comment]
@pmgration @boulaycote 
hey guys 
im using busboy to parse multipart form data like was posted above.
the problem i have is that in different environment i get req.body undefined which causes exception when
setting the fields. do u have any idea why is this happening?

**Comment by nicejwjin** [comment]
@mushkab My project is working well still. Could you specify your case?

**Comment by mushkab** [comment]
@nicejwjin when i handle http post in server (from third party application - webhook) with content type of multipart form data(parse it in router.onbeforeaction), i get req.body undefined in production environment. this does not happen in development where req.body is object({}).  the post call is totally equal in both cases.
when req.body is undefined it causes error when setting fields in the code above.

 busboy.on("field", function(fieldname, value) {
            req.body[fieldname] = value;
        });

wondering what causes this.

**Comment by maxzzznz** [comment]
@mushkab I had the exact problem as you, it seems that the body object does not exist at 'onBeforeAction' time. My quick work around the problem was to extend the request object with a new postData 'sub-object'. I did this with underscoresj which I was already using in my project.

In the end this is working for me:

```javascript
if (Meteor.isServer) {
    var Busboy = Meteor.npmRequire("busboy"),
        fs = Npm.require("fs"),
        os = Npm.require("os"),
        path = Npm.require("path");

    Router.onBeforeAction(function (req, res, next) {
        var filenames = []; // Store filenames and then pass them to request.
        _.extend(req, {postData: {}});

        if (req.method === "POST") {
            var busboy = new Busboy({ headers: req.headers });
            busboy.on("file", function (fieldname, file, filename, encoding, mimetype) {
                var saveTo = path.join(os.tmpDir(), filename);
                file.pipe(fs.createWriteStream(saveTo));
                filenames.push(saveTo);
            });
            busboy.on("field", function(fieldname, value) {
                req.postData[fieldname] = value;
            });
            busboy.on("finish", function () {
                // Pass filenames to request
                req.filenames = filenames;
                next();
            });
            // Pass request to busboy
            req.pipe(busboy);
        } else {
            this.next();
        }
    });
}
```

Then I can get access to the POST fields and their values using this in my route:

```javascript
this.request.postData
```

**Comment by harvinder34** [comment]
it does not return any file name or data
