### ISSUE TITLE
static files on Modulus CLOUD_DIR

### ISSUE THREAD

**Issue by doubletaketech** [iron-meteor/iron-router#932]
Modulus.io creates a CLOUD_DIR env variable for persistent file storage. This attaches an  /App-Storage directory.  I upload images to this location.  This is not in my public folder, but needs to be treated as such.

When <img src="/app-storage/myimage.jpg"> this image doesn't load.  I see route doesn't exist message in the console.

How do I set up a route for /app-storage that serves up the images?

Thanks,
Don

**Comment by gjgiraldo** [comment]
This i another  solution 

  app.get('/app-storage', function (req, res, next) {
         //process.env.CLOUD_DIR="/app-storage"
     //    console.log(getFiles(process.env.CLOUD_DIR))
         console.log(getFiles("app-storage"))
   
         next();
     });

     function getFiles(dir, files_) {
         files_ = files_ || [];
         var files = fs.readdirSync(dir);
         for (var i in files) {
             var name = dir + '/' + files[i];

             if (fs.statSync(name).isDirectory()) {
                 getFiles(name, files_);
             } else {
                 files_.push(name);
                 stat = fs.statSync(name);
                 console.log(name + " " + stat.size);

                 resp.write(name + " > "+  stat.size  + "  - bytes" + "<hr>")

              
             }
         }
         return files_;
     }

**Comment by gjgiraldo** [comment]
making test i found teh solution to render files from app-storage  in modulus.io as static files

here is in local


replace /app-storage for process.env.CLOUD_DIR in modulus to work

app.get('/app-storage/:file', function (req, res, next) {
    //process.env.CLOUD_DIR="/app-storage"
    var f = req.params.file;

    console.log("file " + f)

    var filecontent = fs.readFile(__dirname + "/app-storage/" + f, function (err, data) {

        res.end(filecontent);

        console.log(filecontent);

    });

    next();
});


and in html
<img src="http://localhost:8080/app-storage/xxxxx.gif" />

gabriel
www.GJGsoftware.com
