### ISSUE TITLE
scroll to top

### ISSUE THREAD

**Issue by ryw** [iron-meteor/iron-router#96]
See https://github.com/tmeasday/meteor-router/issues/71 — moving a project to IronRouter, I need to reimplement this hack.

Should something like this work OK w/ iron-router?

**Comment by williamli** [comment]
I still notice iron router refusing to scroll back to top on my routes. I will try to implement these hacks here.

**Comment by keyscores** [comment]
Is this closed because it was fixed?
+1 for scrolling by default.

**Comment by williamli** [comment]
I still notice this error on 1.0.5

**Comment by adrian-sgn** [comment]
this looks helpful for those that want scroll-to-top by default:

https://atmospherejs.com/okgrow/iron-router-autoscroll

**Comment by x5engine** [comment]
I don't want this to happen! how to disable override the scroll top

**Comment by anish30** [comment]
Deps.autorun(function () {
  var current = Router.current();

  Deps.afterFlush(function () {
    $('.content-inner').scrollTop(0);
    $(window).scrollTop(0);
  });
});

Where it code is writining on render or on event ?
