### ISSUE TITLE
Iron router showing "Organize your meteor application" after bundling 

### ISSUE THREAD

**Issue by jamesfebin** [iron-meteor/iron-router#976]
I recently upgraded to 1.0 . 
Everything works fine while in the development stage
But after i build the package using meteor build and run it

I am taken to a custom iron router page which has the following message

```

Organize your Meteor application.

Router.route('/', function () {
  this.render('Home', {
    data: function () { return Items.findOne({_id: this.params._id}) }
  });
});
```

Router code

```
Router.route "/",
        onBeforeAction:(pause) ->
                if not Meteor.user() and not Meteor.loggingIn()
                        @render('login')
                else
                        @next()
        waitOn: ->
                @subscribe("teamsData")
                Session.set('page','homeFeed')
                Session.set('teamId','')
                Session.set('limit',5)
                Session.set('loggingOut',false);
        action:->
                if @ready
                        @render "feed"
```

**Comment by the1mills** [comment]
I have this issue - everything is fine locally, but once I deploy to meteor.com, then all I get is the iron:router splash and nothing else. I assume it's a server side variable problem, but not sure...

**Comment by marineb** [comment]
Same issue and it just started happening today. Anyone figured it out?

**Comment by thomasgalibert** [comment]
I think you have some issues in production mode (check your
console) that prevent iron-router to work properly. If you fix it,
it's gone be fine.


Le Mer 11 févr 2015, à 17:33, Marine Boudeau a écrit :
> Same issue and it just started happening today. Anyone figured it out?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/EventedMind/iron-router/issues/976#issuecomment-73912805

**Comment by marineb** [comment]
You're right. Thank you!

**Comment by vgauthier** [comment]
Same issue and it just started happening today and nothings from the console

**Comment by quickj** [comment]
@cmather @jamesfebin . 
I have the same issue when it run on the production mode. I see your solution and set a server variable. But i dont konw which variable and how to set it. can you help me.
Very thanks!

**Comment by jamesfebin** [comment]
@quickj I assume some of your apis of iron router are old. Do one thing comment all your routes and just use the / route . Refer iron router documentation. Let me know if it works out

**Comment by quickj** [comment]
@jamesfebin I have commented as you said.But get the same issue "Organize your Meteor application".
I checked the console and find two error:
1. Uncaught Error: Not permitted. Untrusted code may only remove documents by ID. [403]
2. GET https://www.youtube.com/iframe_api net::ERR_INSECURE_RESPONSE
Are these two error caused the problem?

**Comment by Ethaan** [comment]
```1. Uncaught Error: Not permitted. Untrusted code may only remove documents by ID. [403]```

You get this error when you are trying to do the follow

```javascript
Collection.remove({name:someValue}) //will cause [403] erro

//correct way
Collection.remove({_id:this._id})
``

```2. GET https://www.youtube.com/iframe_api net::ERR_INSECURE_RESPONSE```

Check this [SO](http://stackoverflow.com/questions/23688565/failed-to-load-resource-neterr-insecure-response) related

**Comment by quickj** [comment]
It works fine on my local,but get these two error on production mod. So we must add the "_id" field on the "Collection.remove()" function?

**Comment by quickj** [comment]
@Ethaan i dont think these two errors caused the "Organize your Meteor application" issue. I try it on my local and also find these two error but works fine.

**Comment by binhwpo** [comment]
I'm also having this annoying thing after running `meteor add manuelschoebel:ms-seo`

![screen-shot-2015-03-10-at-2 22 45-pm](https://cloud.githubusercontent.com/assets/7647566/6570675/055e117a-c731-11e4-8e0a-ddead24bfc3f.jpg)

Please help. Thanks.

**Comment by llaine** [comment]
+1

**Comment by KFoxder** [comment]
+1

**Comment by satyavh** [comment]
+1

**Comment by cmather** [comment]
happy to accept a pull request to take this out

On Sun, Jun 28, 2015 at 1:47 PM, Satya van Heummen <notifications@github.com

**Comment by raihle** [comment]
Make sure to check your console output for e.g.

    Uncaught TypeError: Cannot set property 'created' of undefined

(In my case caused by javascript referring to a delete template)

Errors like this will still let your app work in development but may cause the above screen when they show up in a bundled app.

**Comment by wesleyfsmith** [comment]
+1

**Comment by Chicooz** [comment]
+1

**Comment by ThomsCass** [comment]
I use iron-router for server side otherwise I use angular-meteor.
+1

**Comment by odb366** [comment]
After I updated to Meteor 1.3 I have the same error. Please help.

**Comment by markmitton** [comment]
+1

**Comment by ThomsCass** [comment]
Here is a workaround has no solution is provided

``` javascript
$(function() {
            setTimeout(function(){
                $( "body div" ).last().remove();
            }, 10);
        });
```

**Comment by Harishgargprince** [comment]
+1

**Comment by baberuth22** [comment]
You have an error in your code.  Check the browser console.

**Comment by zhenwan** [comment]
same here, no error shown in console. Is there a solution yet?

**Comment by paolo-g** [comment]
+1

Seems silly that there is no configuration option to stop this welcome message from showing. Am using the solution @ThomsCass provided in https://github.com/Urigo/angular-meteor/issues/1314 while shouting into a pillow

**Comment by tae-jun** [comment]
+1

**Comment by chrisbutler** [comment]
@paolo-g @tae-jun @ThomsCass added in 1.1.0

**Comment by tae-jun** [comment]
Thanks @chrisbutler !

**Comment by paolo-g** [comment]
Cheers!
